### ISSUE TITLE
Gather basic usage stats

### ISSUE THREAD

**Issue by ivelin** [RestComm/smscgateway#1]
Many users and prospects ask what is the scale of use of Mobicents products. We should add a simple counter in the server to report delivered messages, along with public IP of the server. The aggregated stats from around the world can be reported live back to the community.

This issue is related to 
https://github.com/Mobicents/sip-servlets/issues/60

**Comment by vetss** [comment]
This issue is covered by issue: https://github.com/RestComm/smscgateway/issues/124
and fixed now.
