### ISSUE TITLE
SMSC do not reply to submit_sm from remote esme

### ISSUE THREAD

**Issue by almayeen** [RestComm/smscgateway#114]
This happened after upgrading to 7.1.66

When remote SMPP client submit SMS to SMSC GW nothing happened and no response to esme.

After downgrade to 7.1.63 it's solved.

BR
Hussein

**Comment by nhanth87** [comment]
Hi,
Thanks for your report, can you please give server.log and config xml file?

**Comment by vetss** [comment]
Hello @almayeen 

yes, we are doing some major update, but CI task must work.
1) test please a new build 7.1.67
2) please provide server.log from your bad instanse start, We need it for analisys.

**Comment by almayeen** [comment]
Hi @nhanth87 , @vetss 

Thanks for reply.

Please find the log file in attachment
[server.log.txt](https://github.com/RestComm/smscgateway/files/480646/server.log.txt)

**Comment by almayeen** [comment]
Hi @vetss 

I test 7.1.67 and it's working.

**Comment by vetss** [comment]
Hello @almayeen 

I have checked logs, they looks like it were two instanses of a server run at the same time, not 100% sure. Anyway thanks for feedback.

**Comment by almayeen** [comment]
Hi @vetss 

I will take care about running only one instance. 

Thanks for your support.

**Comment by almayeen** [comment]
Hi @vetss , @nhanth87 

I figured out the reason of issue, because it's happened again after deploying 7.1.71.
The reason was missing of restcomm-slee-ra-http-servlet-DU-2.8.14.jar and restcomm-slee-ra-http-servlet-common.jar.

Sorry for misunderstanding.
