### ISSUE TITLE
Docs: descritpion of TxHttp interface syntax

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#117]
After implementing of https://github.com/RestComm/smscgateway/issues/113 "TxHttp SBB" we need to add a chapter to a manual with description of syntax of HTTP rqeuests, which parameters are available, mandatory / optional, default values.

We can put a new chapter just after "5.5. SMS Home Routing"
with the name "5.6. HTTP interface description"

**Comment by mniemiec** [comment]
[HTTP interface description.docx](https://github.com/RestComm/smscgateway/files/489538/HTTP.interface.description.docx)

**Comment by vetss** [comment]
Fixing by:
https://github.com/RestComm/smscgateway/commit/d341957c4a2064f73513f08076095b9bcf3b886f

**Comment by mniemiec** [comment]
+| smscEncoding | Values can be "GSM7" (usually used for english letters and digits) or "UCS2" (used for arabic, cyrillic, etc letters), default is "GSM7".
+| messageBodyEncoding | Values can be "UTF8" or "UTF16". If parameter is not provided then value depends on "smscEncoding" parameter and it is taken from SMSC properties . Default value is "UTF8".
