### ISSUE TITLE
TxHttpServerSbb:: missing jar for "net.java.slee.resource.http.events.incoming.request.GET"

### ISSUE THREAD

**Issue by inesromdhani** [RestComm/smscgateway#121]
Jboss can't load smsc-services-du.jar 
Component SbbID[name=TxHttpServerSbb,vendor=org.mobicents,version=1.0] depends on EventTypeID[name=net.java.slee.resource.http.events.incoming.request.GET,vendor=net.java.slee,version=1.0] which is not available in the component repository or in the deployable unit<br />

**Comment by vetss** [comment]
Which exactly code version / binary version do you try to use ?
Can you test code from master branch again. Please also take into account that SMSC GW demands now HTTP servlet RA, do not forget to deploy ir.

**Comment by inesromdhani** [comment]
I use code version 7.1.71 from here: https://github.com/RestComm/smscgateway/tree/7.1.71
I don't found where is "net.java.slee.resource.http.events.incoming.request.GET" and please tell me where i can found the HTTP servlet RA? Thank you

**Comment by inesromdhani** [comment]
It works now, it's here https://github.com/RestComm/jain-slee.http/tree/2.8.83/resources/http-servlet
