### ISSUE TITLE
Integrate the Restcomm Statistics

### ISSUE THREAD

**Issue by deruelle** [RestComm/smscgateway#124]
For every SMS sent or received either through SMPP or SS7 we should ping the Restcomm statistics server at the end of the day. The integration on the SMSC side happens through this project https://github.com/RestComm/commons/tree/master/statistics.

Ping me for more guidance

**Comment by vetss** [comment]
Fixing by:

https://github.com/RestComm/smscgateway/commit/16182851c7148f4ca5232338ac238575d1f7de85
https://github.com/RestComm/smscgateway/commit/69f6426276a803d663ec2725c682dc136dfdc89c
