### ISSUE TITLE
TxHttp: HttpUserName field in Sms

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#132]
We need such field for logging (database / CDRs) and to apply mproc rules.
We can try to reuse "ESME name field" or create a new field.
For mproc rules we need to create a special codition to this field.

**Comment by vetss** [comment]
A first fix by https://github.com/RestComm/smscgateway/commit/e23f93f618a253b2147d3576f332c93fe4026432
reusage of esmeId.

**Comment by adamgorak** [comment]
Hi,

you mean we should have some kind of Client Identifier at the HTTP interface for sending SMS?

Regards,
adam

**Comment by vetss** [comment]
Hi @adamgorak 

we have "Client Identifier" == User Name. I think we can reuse them if there is no other customer's requirenments.

The described in this issue topic is: now we use the single field in Sms class (and CDRs, database etc) for both ESME names and HTTP user names. Thia may be not very correct (althow I am not very sure because of current solution is simplier).

**Comment by adamgorak** [comment]
Ok,

then we will have to separate it.

Currently the ClientId (UserName) is used as a target ESME name (one of those from EsmesClusters)?

The ClientId can be used as it is now on the input. However it should not hint the target Esme (or EsmeCluster name)... That will be selected through the MProc rules (RA). Ok, by default (Default MProc RA) the target NetworkId could = ClientId.

Cheers,
adam

**Comment by vetss** [comment]
Hello @adamgorak 

if we are saying for CDR records we export now only "OrigSystemId" fields (not a dest ESME). This one (for which I said we may be need to split to different fields):
	/**
	 * SMPP name of origination esme systemId (SMPP originated) / HttpUser name (HTTP originated)
	 */
	public String getOrigSystemId() {
		return origSystemId;
	}

I may be not fully understand you. "the target NetworkId could = ClientId" The first one is a digital value that means an area that contains a destination for delivering (may be an ESME cluster, SS7 destination, SIP destination). "ClientId (UserName)" - for ESME we have "ESME Name" (as Id) (we can also specify a "Cluster name" if we want to group ESMEs into a cluster), for incoming HTTP connection we have "User Name" as Id.

**Comment by adamgorak** [comment]
Ok,

does it mean, for HTTP there is no routing (ESME Cluster selection), but the target ESME (one from ESME Cluster) is determined based on the User Name used in the HTTP request?

Regards,
adam

**Comment by vetss** [comment]
1) we can not deliver messages to HTTP connector (it is only for message submitting)
2) routing is made by several steps
a) mproc rules specifies networkId (if no rules are applied then it will be delivered into the networkID area vie which a message has come) 
b) then SMSC GW checks which ESMEs / SIP connectors are in the assigned networkID and send it via them. Firstly ESMEs are checked. In our case ESMEs are the only option. If no ESME is configurged then SMSC GW will try to deliver to SS7 network (and will fail in our case). An ESME cluster inside this procesdure is selected
c) for SMPP case ESME is selected inside a selected from step b) cluster.

**Comment by adamgorak** [comment]
Ok,

but I wonder if the ClientId=UserName used in the HTTP request (message submission) is in any way used for the routing (determination of the target NetworkId)?

Regards,
adam

**Comment by vetss** [comment]
"determination of the target NetworkId" is made only inside mproc rules (Arrival trigger) and also inside mproc rules that are invoked after message failures (or just before a next delivering attempt) (say that is a message rerouting).

How it will be done, will "ClientId=UserName" be used or not, is decided in mproc rules code, say by you own.

**Comment by vetss** [comment]
Hello @ovoo-unif 

can we mark this issues as fixed ? We reuse "esmeId" for HTTP userId.
I think we can make of separating of such fields by a separate issue if we do need it.

**Comment by ovoo-unif** [comment]
Yes,

we can close it.

Regards,
adam
