### ISSUE TITLE
Default mproc rules action: changing of source address value

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#134]
We need to add into Default mproc rules a new action : changing of source address value.

**Comment by almayeen** [comment]
Hi @deruelle, @vetss ,

Please assign this to me.

I have question, 
If source address TON must be changed along with new source address, does SMSCGW change it after Default MProc was applied, or I have to update SourceAddrTon in PostArrivalProcessorImpl.updateMessageSourceAddr ?

**Comment by deruelle** [comment]
@almayeen assigned to you. @vetss will come back to you on your other question

**Comment by almayeen** [comment]
@deruelle thanks

**Comment by vetss** [comment]
As for now default mproc rules does not change sourse address digits, ton, npi.
If we need it we need to use:
PostArrivalProcessor.updateMessageSourceAddr()
PostArrivalProcessor.updateMessageSourceAddrTon()
PostArrivalProcessor.updateMessageSourceAddrNpi()
depending on which component you want to change

**Comment by almayeen** [comment]
@vetss 

I will add source address digits, ton and npi to default mproc rule.

**Comment by vetss** [comment]
Hello @almayeen 

I can see https://github.com/RestComm/smscgateway/pull/135 from you but it is closed now.
Do you mean you will provide another PR ?

**Comment by almayeen** [comment]
@vetss

Yes, Please ignore the last PR.

**Comment by almayeen** [comment]
@vetss 

I see in MProcRuleDefaultImpl.java, the PostArrivalProcessorImpl.postNewMessage called before 
updateMessageNetworkId, updateMessageDestAddr, updateMessageDestAddrNpi, updateMessageDestAddrTon...
But as in documentation:
"Once rule match's, and makecopy is set to true, a new copy of SMS is created. If new SMS is created all above parameters like networkidmask, newnetworkid, newdestton, newdestnpi, adddestdigprefix will be applied to new SMS"

Should I create new issue for that, or I can add it to this PR?

**Comment by vetss** [comment]
@almayeen 

please follow the type how it is implemented in "onPostArrival"
You can add you code at the end. Below is an example of how it was done for dest addresses:

``` java
        if (this.addDestDigPrefix != null && !this.addDestDigPrefix.equals("") && !this.addDestDigPrefix.equals("-1")) {
            String destAddr = this.getAddDestDigPrefix() + message.getDestAddr();
            factory.updateMessageDestAddr(message, destAddr);
        }

        if (this.newDestNpi != -1) {
            factory.updateMessageDestAddrNpi(message, this.newDestNpi);
        }

        if (this.newDestTon != -1) {
            factory.updateMessageDestAddrTon(message, this.newDestTon);
        }
```

**Comment by almayeen** [comment]
@vetss 

Please note the this code:
if (this.makeCopy) {
            MProcNewMessage copy = factory.createNewCopyMessage(message);
            factory.postNewMessage(copy);
        }
which in begin of  onPostArrival.

So "message" have original values when copy will be done.

We need to move the above code to the end of onPostArrival.

**Comment by vetss** [comment]
"if (this.makeCopy) {" - this is triggered only if you want to make a copy of a message.
Anyway please do not change the processing logic. If you really want to make two actions (message copy making and source address changing) then yes actions will be applied to an original message, not to a copy. Let me check how it works and recheck the manual.

**Comment by almayeen** [comment]
Ok, i will add PR only for source address changing.

**Comment by vetss** [comment]
Hello @almayeen 

I have added you update https://github.com/RestComm/smscgateway/pull/140
 into SMSC GW master branch, thanks for your work.
