### ISSUE TITLE
Better Document Home Routing Feature

### ISSUE THREAD

**Issue by deruelle** [RestComm/smscgateway#138]
http://documentation.telestax.com/core/smsc/SMSC_Gateway_Admin_Guide.html#sms-home-routing  section only talks about Home Routing. But within Home Routing there is also Transparent and Non-Transparent. Initially we implemented only Non-Transparent as you can read from http://documentation.telestax.com/core/smsc/SMSC_Gateway_Admin_Guide.html#_smsc_gateway_server_hr

As I understand, even Transparent mode is supported now and I think we haven't documented it anywhere. 

@vetss can you confirm and update the documentation on that ?

**Comment by vetss** [comment]
We have to implement https://github.com/RestComm/smscgateway/issues/139 before we may update the manual.

**Comment by vetss** [comment]
Fixed by:

https://github.com/RestComm/smscgateway/commit/afbfb98053aac654c3a15dea19b856c690c1d549
