### ISSUE TITLE
Multi-session support for ESME

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#143]
As for now SMSC GW does not support several concurent connections for an ESME. If we need several connections we have to create several ESME instanses that make configuring more complicated.

To solve it we need add some other class - Session that will be hosted by Esme class and change the logic of Emse class usage.

PS: Let's think also for keeping of some Emse parameters that are unique for Esme cluster at the Cluster level to avoid possible wrong configuring of different ESMEs in the same cluster. We have a separate issue for this case:
https://github.com/RestComm/smscgateway/issues/48

**Comment by faizann** [comment]
Do note that multiple SMPP connections to same ESME will cause conflicts in SmppTransactionHandles creation logic reported here.

https://github.com/RestComm/smscgateway/issues/142

**Comment by vetss** [comment]
Hello @faizann 

I understand that we need to make a major change in existing ESME logic to keep SMPP part workable.
Thank you for helping of a problem investigating.
