### ISSUE TITLE
CDRs to escape comma and newline charactes from first 20chars

### ISSUE THREAD

**Issue by faizann** [RestComm/smscgateway#153]
CDR generator takes first 20 chars of a text message and logs it to the file. The extended error is logged after the message. This means that if there are commas in the message then the error field is not at a precise index in the CSV row index.
I suggest to encapsulate Text into quotes so that everything within it is parsed as one text field. 

Another issue is new line characters which should be escaped with `\\n` so that one CDR line is one actual text line and not multiple lines.

**Comment by vetss** [comment]
Hello @faizann 

Your issue is reasonabe. We have also CDR issues: #94, #154
The solution may be just replace "," and "\n" characters from a message field by characters "\," and "\n" (I mean just "\" + "n" and not a CR character)
Do you want to contribute it ?

**Comment by faizann** [comment]
Hi

I am up for it. I can contribute.

**Comment by deruelle** [comment]
@faizann were you able to work on this one ?

**Comment by faizann** [comment]
Hi

Not yet. Will get on it next week.

**Comment by deruelle** [comment]
@faizann happy new year ! Just wanted to check if you had time to make progress on this albeit the holidays ?

**Comment by faizann** [comment]
Hi Jean

I did the code for the initial ticket specs. The other field that I suggested to add requires more work. Should have the pull request by mid next week.

**Comment by deruelle** [comment]
@faizann great thanks !

**Comment by deruelle** [comment]
@faizann just checking in to see if you had time to make the pull request on this ?

**Comment by vetss** [comment]
Thanks @faizann for your update. I have added your commit.

Fixed by:
https://github.com/RestComm/smscgateway/commit/8903a16b86be14beb4752f6afacb7e201124bc3c
https://github.com/RestComm/smscgateway/commit/c802d41bcf7db3703d140baf5e589a4674fa47f5
