### ISSUE TITLE
Separating of docs for already separated SMPP RA

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#164]
We have swithced to a separated SMPP RA https://github.com/RestComm/smscgateway/issues/159.

But the manual of ESME configuring is still on board of SSMC GW Admin guide. We need to create a separate manual inside SMPP extentions that explains configuring of SMPP part (SMPP server and ESMEs) and then point from SMSC GW to that part.

**Comment by vetss** [comment]
The issue in smpp-extensions: https://github.com/RestComm/smpp-extensions/issues/1

**Comment by olenara** [comment]
@vetss prepared smpp-extensions man and @satanatoly prepared man for smpp ra. This is done.

**Comment by gsaslis** [comment]
@olenara could you please share some links as to where these manuals are now, as I'll need to see how to best incorporate them into our documentation site?
