### ISSUE TITLE
Generation of CDRs on message rejections

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#165]
As for now SMSC GW generates CDRs only for messages that have been successfully accepted by SMSC GW. We need add of CDR generating also for the case when a message is rejected.
A message can be rejected by:
- message accepting for the connector is forbidded by a connector at SMSC GW level
- by request to a diameter server
- by mproc rules - Arrival trigger
- by mproc rules - HrSri trigger (HomeRouting procedure bypassing)

This option must be configurable and turned off by default (parameter "CDR generating for rejected messages").

**Comment by vetss** [comment]
Hello @mniemiec 

I have checked your PR https://github.com/RestComm/smscgateway/pull/233

My comments:

1) all these messages must be turned off by "if (smscPropertiesManagement.isGenerateRejectionCdr()) {"
2) not all cases are covered - examle - TxServerSmpp - onSubmitSmLocal() - the case of ESME limitation
        CheckMessageLimitResult cres = esme.onMessageReceived(1);
        if (cres.getResult() != CheckMessageLimitResult.Result.ok) {
3) this part is more complicated. We can not reuse "CdrGenerator.generateCdr(sms, ...);" method for all new cases. The reason Sms object is not defined sometimes. And invoke of the methos in the way like:
"generateCDR(null, CdrGenerator.CDR_SUBMIT_FAILED_ESME, e.getMessage(), false, true);"
will throws an Exception further. From my point of view we need to introduce a special method "generateCDR(....)" that will accept data in "source objects" (not from Sms object).
For example generateCDR(sourceAddress, destAddress, message, ....);
This method will be used for submitting part.

**Comment by mniemiec** [comment]
@vetss 
The newest version of code regarding your comments is here:
https://github.com/mniemiec/smscgateway/commits/smsc_39_merge
We are waiting for review from your side.

**Comment by vetss** [comment]
Hello @mniemiec 

I have seen your commit "CDR on message rejection corrections".
It will be included into the next rekeae iteration

**Comment by vetss** [comment]
Hello @mniemiec 

we are processing and testing your PR https://github.com/RestComm/smscgateway/pull/233
I will let you know when we finish.

**Comment by vetss** [comment]
It is fixed now
