### ISSUE TITLE
Adding of new networkId parameter for TxHttp UserAccount

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#171]
We need to add of new networkId parameter for TxHttp UserAccount. 
If a user specifies the value >=0 then this value will be used as a networkId value via which a message has come to SMSC GW,
If a user specifies the value <0 then a default SMSC GW level value will be used.
Default value: -1

**Comment by vetss** [comment]
Commits: 
e514d6fb4afe4e21628d8c7d6e5f47bf6a1912e3
23b6f73c39e4ad8a9d2b61c1d625e1764a0e92d6

Missed:
- in your manual updaye you need to mention of values for the case "value<0". In this case a "Default networkId area" from "HTTP settings". We need to add a link in the manual for that chapter that set this value.
- we need to update CLI helepr files in the folder core/oam/cli/src/main/resources/help - 
smpp_httpuser_add.txt
smpp_httpuser_modify.txt

**Comment by twob2** [comment]
Hi,

I've done the needed fixes. The new commit (49fd92d) is added to the PR (the same).

I don't understand:
> "We need to add a link in the manual for that chapter that set this value."

Please let me know if it is OK or not now.

Regards,
adam

**Comment by vetss** [comment]
ok, I will check the commits

A link to a manual:
For example a chapter "=== Default messaging mode" has a tag "[[_httpdefaultmessagingmode]]"
if you refer to this chapter you need to refer to this tag

**Comment by vetss** [comment]
Fixing: 

https://github.com/RestComm/smscgateway/commit/51486382f545bab909fdfc6f1d5cbcce9eab800d
https://github.com/RestComm/smscgateway/commit/0ba88b6bf7ec9c4d6bafbf2bc1ed05241e74f010
https://github.com/RestComm/smscgateway/commit/1e3bbb52658f985bbb9b5d68231825d4a0b71fa7
https://github.com/RestComm/smscgateway/commit/2e7ff3bb2a2ac42baab43127d1e1aee9dcd218f7
https://github.com/RestComm/smscgateway/commit/08194f3b5e94a9ed85352216c496b7b6c4240590
https://github.com/RestComm/smscgateway/commit/9771e6ed8cc57e6858551c0ae354d54f8629c467
