### ISSUE TITLE
Authentication with Cassandra by using user and password

### ISSUE THREAD

**Issue by nhanth87** [RestComm/smscgateway#176]
At that time, SMSC is using default user and password (cassandra/cassandra) to connect with database. But Cassandra database can have multiple user/password for their keyspace, we need to care of it

**Comment by scottbarstow** [comment]
@nhanth87 can we bump this up to a patch release? we have to have this externalized for @abdulazizali77 current work.

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/862d2a4df25b53f8a5e8d14792846c4473b9a1d6
https://github.com/RestComm/smscgateway/commit/b8fa5c0b7e9134d892030e7ba375e7759fe433e4
