### ISSUE TITLE
Making of message routing depending on TVL value

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#179]
We need to implement functionality when SMSC GW will change networkId depending on a value of some TVL field.

We need to implement:
- TlvSet MProcMessage.getTlvSet(); - getting of a list of TLV values.
- PostArrivalProcessor.removeTLVParameter(short tag); - remove of TVL parameter from a message

We need to update default mptoc rules by:
- option:
tlv_byte_11 333
tlv_int_11 333
tlv_string_11 333
 - true if a TLV with tag 11 (byte, String or C-Octet String value types) == 333
- action: "remove_tlv 11" - remove TLV with tag 11

**Comment by scottbarstow** [comment]
@abdulazizali77 please provide estimates

**Comment by abdulazizali77** [comment]
@scottbarstow my estimate should at least be double of @vetss , this would be inclusive of setting up a local environment and testing

**Comment by vetss** [comment]
Hello @abdulazizali77 

I have checked your update https://github.com/RestComm/smscgateway/pull/183/commits, thanks for it.
I have added your commit with my little fixes. My comments:

1) removeTlvParameter(MProcMessage message, short tag); must have an parameter message for processing of a concrete message. I have adding this.

2) Having of a parameter tlvValueToMatch as byte[] is rather complicated to manege from GUI / CLI from my point of view. I do suggest to have a String value. Then it will be easy to have getter / setter, CLI / GUI processing. But a next problem is that we need to compare values that may be different for different TVL types. To overcome it I suggest to have different implementations for following different TLV types:
- byte
- short
- Integer
- C-Octet String (ASCII encoded String value)
We have TLV methods for them: getValueAsByte(), getValueAsShort(), getValueAsInt(), getValueAsString(). I suggest ti implement 3 types so far (CLI options):
tlv_byte_11 333
tlv_int_11 333
tlv_string_11 333

**Comment by vetss** [comment]
Partly fixed by:
https://github.com/RestComm/smscgateway/commit/0ad0472394bda823b1b217fa36575c4942741781
https://github.com/RestComm/smscgateway/commit/e2417e5020939589ebb3b11cc84827e9eb5d1f2e

**Comment by abdulazizali77** [comment]
Thanks @vetss. I will address the additional fixes tomorrow/next few days
For 4) Should we maintain our own hashmap of allowable custom parameters OR should we allow any and all adhoc parameters set by the user?

**Comment by vetss** [comment]
@abdulazizali77 

for 4) I think we cal allow any tag value (not from some a specified list). If you asked something esle please comment

**Comment by abdulazizali77** [comment]
thanks @vetss you answered my question

**Comment by abdulazizali77** [comment]
@vetss, One thought/question for 2)
should we allow limited regex patterns for tlvTagToMatch and or tlvValueToMatch ?
eg 
tlv_byte_.
tlv_byte_1.
tlv_byte_1.
tlv_byte_1..
Just a thought, its not easy to implement

**Comment by vetss** [comment]
@abdulazizali77 

I do not think we need a regex pattern for a TLV tag matchng. I beleive we will know a concrete value of TLV tag. Or you have scenarious when we need it ?

Check also my comment in
https://github.com/RestComm/smscgateway/issues/180

Please let me know if you have some doubts of desired approach.

**Comment by vetss** [comment]
Hello @abdulazizali77 

I checked your update in https://github.com/RestComm/smscgateway/pull/190 and have some comments:

1) Your solution is:
        short tlvTagToMatchString = -1;
        String tlvValueToMatchString = "";
        short tlvTagToMatchInt = -1;
        int tlvValueToMatchInt = -1;
        short tlvTagToMatchByte = -1;
        byte tlvValueToMatchByte = -1;
I think it is simpler to have following values:
        short tlvTagToMatch = -1;
        TlvValueType tlvValueTypeToMatch = null;
        String tlvValueToMatch = null;
and
enum TlvValueType { byte, int, String };
When making of matching we need cast byte / int TLV values into String firstly and then compare it with tlvValueToMatch
This solution seems to me more clear. 

2) getRuleParameters() - 
a) when you are describing a condition (like "tlv_byte_11 333") you need to put it into a condition section (before newNetworkId in your case). "tlvTagToRemove" - at the end because it is an action. We have firtsly all conditions and then all actions.
b) we need to have "tlvTagToMatchString" parameters names like we have in CLI interface "tlvString_11" or "tlvByte_12" or "tlvInt_13" in our case, you can check how other name correlate to CLI name. Here we need to have names like CLI commands (not like tlvTagToMatch / tlvValueTypeToMatch / tlvValueToMatch)

3) we need to add getters / setters for GUI. For "remove_tlv 11" it is similar like others (one getter / setter). But for conditions like "tlv_byte_11 333" we need 3 getters / setters (for tlvTagToMatch / tlvValueTypeToMatch / tlvValueToMatch). We need to add them into MProcRuleDefaultImpl and MProcRuleDefault interface.

4) finally we need to update GUI and manual

May I ask you to refactor code and provide a new update.

**Comment by abdulazizali77** [comment]
Thanks @vetss , i have updated the PR, please have a look.
Issues:
-Confused/Uncertain. Should the conditions/commands be "tlv_byte_11 333" OR "tlvbyte_11 333" ? I have left it at "tlv_byte_11 333"
-Could have defined TlvValueType in a separate enum class file or defined elsewhere.
-I would like to update the GUI and docs in a separate PR

**Comment by vetss** [comment]
Hello @abdulazizali77 

I have added your commit and add my fix. My fix is for default values, values checking and a way how to load / store ENUM values.

> -Confused/Uncertain. Should the conditions/commands be "tlv_byte_11 333" OR "tlvbyte_11 333" ? I have left it at "tlv_byte_11 333"

Let it be "tlv_byte_11 333" as we have now

> -Could have defined TlvValueType in a separate enum class file or defined elsewhere.

Check my update, I fixed it.

> -I would like to update the GUI and docs in a separate PR

Please go ahead to finish the issue and make testing at a live server.

**Comment by abdulazizali77** [comment]
thanks @vetss

**Comment by vetss** [comment]
Hello @abdulazizali77 

have you finished all updates for this issue ? Have you tested you work at a live server ?
Does GUI / CLI management work for new parameters ? (if not all is implemented we need to finish it)
We need also to update the manual - this chapter :
http://documentation.telestax.com/core/smsc/SMSC_Gateway_Admin_Guide.html#_mproc_rules_fundamentals

**Comment by abdulazizali77** [comment]
apologies for the late update @vetss 
-we have tested on live staging server, Default mproc rule works fine.
-have pushed GUI CLI and docs PR in #205

**Comment by vetss** [comment]
Hello @abdulazizali77 

the work is finished by https://github.com/RestComm/smscgateway/pull/205
Thanks for your update.

**Comment by abdulazizali77** [comment]
thank you @vetss
