### ISSUE TITLE
http get replace + with space number

### ISSUE THREAD

**Issue by nhanth87** [RestComm/smscgateway#195]
http get replace + with space number

We need to remove + instead adding space

**Comment by vetss** [comment]
@nhanth87 

May it be beacuse of HTTP get itself replaces "+" to space ?
We can try to use "%2B" instead of "+".

But as I tested SMSC GW doesn not remove "+" at all. So we may not send a dest address with "+". We must send only digits.

**Comment by mniemiec** [comment]
PR for the issue: https://github.com/RestComm/smscgateway/pull/196
