### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by freemanpolys** [RestComm/smscgateway#2]
Hi,
There is dependencies problem while trying to install (mvn install)
Find the error below : 
```
[ERROR] Failed to execute goal on project smpp: Could not resolve dependencies for project org.mobicents.smsc:smpp:jar:2.0.0-SNAPSHOT: Failure to find org.mobicents.protocols.ss7.management:shell-server-api:jar:2.1.0.FINAL
```

Regards,

**Comment by vetss** [comment]
We have updated SMSC GW release scripts, such error must not come more

**Comment by Dirler** [comment]
Hi All,
Currently very similar issue exist:
> [ERROR] Failed to execute goal on project smpp: Could not resolve dependencies for project org.mobicents.smsc:smpp:jar:7.0.46: Could not find artifact com.fizzed:ch-smpp:jar:5.0.10-SNAPSHOT in mobicents-public-repository-group (https://oss.sonatype.org/content/groups/public)

Looks like 5.0.10 snapshot of ch-smpp doesn't exist (or gone):
https://oss.sonatype.org/content/groups/public/com/fizzed/ch-smpp/

Can somebody take a look, both exits (5.0.9 and 6.0.0-netty4-beta-3) ch-smpp versions - produces compilation errors.
Thanks.

**Comment by vetss** [comment]
Hello,

you need to download and compile locally an updated cloudhopper-smpp code from
https://github.com/RestComm/cloudhopper-smpp
