### ISSUE TITLE
MProcMessage - adding of MessageId parameter

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#200]
We need to add  of MessageId parameter into MProcMessage mproc rules interface.

**Comment by vetss** [comment]
Partly fixed by:
https://github.com/RestComm/smscgateway/commit/797c56f9878ca3f2a057ba7a7d47af922e033da0
https://github.com/RestComm/smscgateway/commit/cef89e82a0e22bce62dcac72191ea94203b5d6e9

**Comment by vetss** [comment]
Hello @ovoo-unif , thanks for your update.

my comments
1) we need to have MessageId as long because it is long in the current SMSC GW design
2) correlationIdValue.getCorrelationID() is not MessageId but some other parameter
3) we need to update a manual - update interfaces for mproc rules

I have fixed 1) and 2)
Please add a fix for 3)

**Comment by ovoo-unif** [comment]
Ok,

I've asked Michal to take it after he's done with CSV Stats Printer.

Regards,
adam

**Comment by mniemiec** [comment]
fix for 3): https://github.com/RestComm/smscgateway/pull/204

**Comment by vetss** [comment]
Hello @mniemiec 

I have committed your uodate https://github.com/RestComm/smscgateway/pull/204
The issue is fixed.
