### ISSUE TITLE
Adding of processing time into CDRs

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#201]
We need to add of processing time into CDRs.

Adding of such parameters must be configurable.

**Comment by vetss** [comment]
Partly fixed by:
https://github.com/RestComm/smscgateway/commit/2f403a7ed3d1a181aa1821f23b8498a932d94347

**Comment by vetss** [comment]
Hello @ovoo-unif , thanks for your update.

my comments:

1) we need to have processing time as a configurable (turned off by default) option (by a single parameter "Delay parameters in CDRs")
2) Why have you  "smsEvent.getSubmitDate()" the second time (we already have it as a firts parameter). May be it is enouph to have only one entry ?
3) we need to update a manual - update http://documentation.telestax.com/core/smsc/SMSC_Gateway_Admin_Guide.html#_monitoring_smsc_cdr_log

Please add a fix for 1), 2) and 3)

**Comment by ovoo-unif** [comment]
Ok,

I've asked Michal to take it after he's done with CSV Stats Printer.

Regards,
adam

**Comment by mniemiec** [comment]
extra fix: https://github.com/RestComm/smscgateway/pull/207

**Comment by vetss** [comment]
Hello @mniemiec 

I accepted your PR https://github.com/RestComm/smscgateway/pull/207, thanks for your work.
I added my extra commit also: https://github.com/RestComm/smscgateway/commit/a0a2b53d3698667145d9eac9cc1736cd647e2be8

My comments:
1) you have not fully updated CLI interface / helpers. Please check my added commit to find out which missed parts were at yout update.

2) I think you wanted to add 3 counters with following descriptions:
.PROCESSING_TIME
A processing time between a CDR generation time and a message submit time in milliseconds.
.DELIVERY_DELAY
A processing time between a message delivery (or failure) time and a message submit time in milliseconds.
.SCHEDULE_DELIVERY_DELAY
A processing time between a time for which a message is scheduled and a message submit time in milliseconds (this field is empty if a message has not be scheduled to a database but was delivered immidiately).
Please confirm.

3) I checked your values in the CDR:
a) counters 1) and 2) have about same values (because time of end measurement are measured in the same thread one after one in several lines).
b) counter 3) always empty (at least in my testes) even a message was stored into cassandra database (: . It looks like that "smsEvent.getScheduleDeliveryTime()" is not filled at the logging time.
c) counter 1) (and 2) ) may calculate very much time in case of a message was stored into a database (say how much time a message was stored into a database, not a really processing time).
d) couner 1) can be easily calculated from other fields of a CDR record.

A question - do we really need such CDR fields ? Please comment. I do not see a value of fields 2) and 3) at least.

**Comment by ovoo-unif** [comment]
Hi Sergey,

regarding 1 - Yes. But I understand - nothing to be done on our side.
regarding 2 - Exactly.
regarding 3 - So finally, let us remove DELIVERY_DELAY field. And let us try to find out why the ScheduleDeliveryTime valiue is not available in the CDRs (even in the Normal S&F and after temp failure).

Regards,
adam

**Comment by mniemiec** [comment]
Hi Sergey,

I created an extra fix for the issue regarding the comments above: https://github.com/RestComm/smscgateway/pull/220. I have tested a ScheduleDeliveryTime field also. I set the 'schedule delivery time' to 5min in SMPP simulator and after sending a message the SCHEDULE_DELIVERY_DELAY field was set in generated CDR. So it seems to work fine in that case.

Regards,
Michał

**Comment by vetss** [comment]
Hello @ovoo-unif 

I added your PR https://github.com/RestComm/smscgateway/pull/220 and an extra commit from my side.
I think we can close the issue.
