### ISSUE TITLE
SLEE based statistics in TX/RX SMPP Services.

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#202]
We need to add SLEE based statistics in TX/RX SMPP Services.

**Comment by vetss** [comment]
Partly fixed by:
https://github.com/RestComm/smscgateway/commit/81af20bb8350a7540b72b8248bed99481291d1d1

**Comment by vetss** [comment]
Hello @ovoo-unif , thanks for your update.

my comments:

1) we need to update a manual - adding a new chapter into http://documentation.telestax.com/core/smsc/SMSC_Gateway_Admin_Guide.html#_smsc_stat_get
Please add a fix it.

**Comment by ovoo-unif** [comment]
Ok,

I've asked Michal to take it after he's done with CSV Stats Printer.

Regards,
adam

**Comment by mniemiec** [comment]
PR for issue: https://github.com/RestComm/smscgateway/pull/210

**Comment by vetss** [comment]
Hello @mniemiec 

I have added your manual update (and added a link to a web console there). Thanks for your work.
We can close the issue.
