### ISSUE TITLE
Adding of limitation of a RxSmpp sending messages / segments to a same dest address

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#208]
We have some operators that have a requirenment:
we can not send more then 1 (or may "x") message(s) (or segments if SMSC GW is splitting a long message before sending) before a response from a peer, but we can send more messages for different destination addresses.

So we need to implement :
- a configurable limit of sent unconfurmed message count for a dest address per an ESME (default value is 0 - no limitations)
- a functionality in RxSmpp fo fit this

**Comment by ovoo-unif** [comment]
Hi Sergey,

when the message parts are send - they can be sent to different ESMEs within one and the same cluster, right?

If so, we need to have queue (MQF monitoring) - per cluster per destination.

Regards,
adam

**Comment by vetss** [comment]
Messages for the same destination address can be sent via different ESMEs but if it is a part of a split message then all parts will be sent via a single ESME.

I do not fully understand for what is "MQF monitoring". Message limitation in terms of this issue is per a dest address, not per a cluster / ESME. This means that a next message to the same dest address will be sent only after a previous message response even a new message will be routed to another ESME in the cluster.

**Comment by ovoo-unif** [comment]
Ok,

if the multipart SMS parts are sent over one and the same ESME, then we can accept it (queue per ESME per destination).

Perhaps it is not ideal, but at least it will solve the issue with MQF at sending of long messages.

Regards,
adam

**Comment by ovoo-unif** [comment]
Sergey,

and question from customer:

"but the question is what will happen in case one of the messages on the queue is failed to another reason or even for MQF what the system will behave?"

Regards,
adam

**Comment by vetss** [comment]
If a message / message part fails for some reason like wrong SMPP response from a peer (like MQF) then all watiting messages / message parts will not be sent this delivery attemt. In case of temporary failure messages that are storeAndForward will be resent in the next sending attempt for this destination address.

This part of functionality is not changing by this issue.

**Comment by vetss** [comment]
Fixes in smpp-extension part:

https://github.com/RestComm/smpp-extensions/commit/8dc7cf2d3fa5c83cf48bfcddcbbf93da5da6b324
https://github.com/RestComm/smpp-extensions/commit/77402be80ac04731421eae6f2f65c95d47ee2293
