### ISSUE TITLE
Statistics Fields - Number of Queued Messages

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#215]
We need to implement a counter “number of pending for delivering messages stored in the database (cassandra).”

Cassandra database architecture does not allow of easily counting of pending messages by a simple SQL request. Messages. A request “select * from SLOT_MESSAGES_TABLE_YYYY_MM_DD where IN_SYSTEM=0” takes much time because we do not have an index for the field (IN_SYSTEM) and cassandra will need to look at the all of pending messages. Making an index for this field is not also recommended by cassandra because it has only two values (say true / false), we may make indexes only with a big count of values for good productivity.

That is why we need to implement another solution without of usage of database fields checking.
We need to create a new table “PENDING_MESSAGES” with structure:
CREATE TABLE PENDING_MESSAGES  (
  day ascii,
  stored_messages counter,
  sent_messages counter,
  PRIMARY KEY (day)
);
Day - is a primary key with info of a day in format “2017_05_31”.
We increment stored_messages counter when we store a new message into a database.
We increment sent_messages counter when we mark a message in a database as delivered.

Points of a counter incrementing / decrementing :

Incrementing of a counter stored_messages (a message is stored into a database)
c2_createRecordCurrent() - after “ResultSet res = session.execute(boundStatement);” + increment stored_messages
Incrementing a counter sent_messages (a message is marked as “SENT” in a database)
c2_updateInSystem() - if isSystemStatus==DBOperations.IN_SYSTEM_SENT - inside “if (sms.getStored()) { ... } block !!!! ” - increment sent_messages

When SMSC GW start we read counters for today and next 2 days and calculate a message count and then keep this value updated when delivering process. SmsSetCache can hosts this value.

Results of counter calculating:
“smsc stat get” CLI command “MessagesPendingInDatabase” value
In SMSC statistics as “MessagesPendingInDatabase” counter
Testing:
Add a unit test for updating / reading new counters to / from cassandra database and also a case when we read a counter for a day for which we do not have yet a record value in the database (0 must be returned)
A test at a live server with CLI / GUI results checking. We need to store some records to database, check valuers, waits till message delivering, check values. Then we need to restart a server and check that a counter is ok after restart
performance testing to see the impact of counters and potentially batch on the CI env performance job

**Comment by vetss** [comment]
- why do we have in getStat(String[] args):
		long currTime = new Date().getTime();
		long startOfTheDay = currTime - currTime%(24*60*60*1000); 
?
- let's put "logger.warn("Started SmscManagemet " + name);" at the end of a start() method of SmscManagement
- getStoredMessagesCounter and getSentMessagesCounter - PreparedStatement - can we avoid of "ALLOW FILTERING" at the statement ?
"ALLOW FILTERING" from cassandra's point of view rather bad operation that can lead timeouts when we have many records. I understand that we will not face a big record count at least first time of this
database requests processing but let's make processing "in proper way" without "ALLOW FILTERING". The condition will be "=" in this case and we will make several database requests.
- SmsSetCache - I see a way you keep data in getMessagesStoredInDatabase() (and at a second method). No removing, and we can keep here many days. May be we can have some tool for removing of extra records from a collection.
- Statistic in SmscStatProviderJmx - I think we need to have "MsgPendingInDb" - with CounterType.Maximal. Other two counters are useless in the way we calculate it. Maximal is needed to have max values when aggregating that will show max load.

**Comment by olenara** [comment]
Fixed by:
10da2a546feec772660b93930823f5b908828637
c11c3a46278a282d10b0dd2c95f94a3c953d9c65
61e585df9c066c904b60c2902778cfbd81bc875f
a1d18b3f88e0e8240de35bc6b502bf05fca9982b
1685e9e720dc7afe4b3fb8c7fb5d6bb7074f2f1e
44eda184b034c263e29dbc0a0f0952b09df38da8
b29093f02b20b678be410117cecab24151e9967e

**Comment by olenara** [comment]
Code has been merged to master.
