### ISSUE TITLE
CDR Enhancements - detailed CDRs

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#216]
A suggested list of fields :

1) CDR recording timestamp
2) Event type
3) ErrorCode (status)
4) MessageType
5) Status code:
  a) Out SMPP response value (for out_smpp_rejected case - received non zero smpp response code when message sending, 0 for other cases)
  b) In SMPP response value (for in_smpp_reject_* cases - sent non zero smpp response code when message receiving, 0 for other cases)
  c) In HTTP response code (for in_http_reject_* cases - sent non zero http response code when a http response sending (code in the message body), 0 for other cases)
6) CorrelationId (== messageId of a message)
7) OrigCorrelationId (== messageId of an original message if this a recognized DLR and an original message is found, else - empty value)
8) DlrStatus (value of “stat” field of DLR. Empty if it is not a DLR. “err” if it is a DLR but the field is not parsed or have different values in text and TLV parts)
9) mprocRuleId (that led a message drop / reject, for in_smpp_reject_mproc, in_smpp_drop_mproc, in_http_reject_mproc, in_http_drop_mproc, else - empty value)
10) ESME name (via which a message has come to SMSC for an IN case or has sent to SMSC GW via which a message has left SMSC GW for an OUT case, an empty value for other cases)
11) Timestamp A
12) Timestamp B
13) Timestamp C
14) Source IP (if a value is available for a channel connection)
15) Source port (if a value is available for a channel connection)
16) Dest IP (if a value is available for a channel connection)
17) Dest port (if a value is available for a channel connection)
18) SequenceNumber (for SMPP messages both for sending / receiving)

Below is a definition for fields values:

** Event types:

a) “In” (a result of message receiving) - we cover only smpp and http sides this step

in_smpp_received (a message is accepted from smpp connector)
in_smpp_reject_forbidden (smpp msg is rejected - reason: administrative reasons - SMSC is stopped or paused, cassandra database is not available, all messages from SMPP connector or a concrete ESME are forbidden)
in_smpp_reject_cong (smpp msg is rejected - reason: congestion at SMSC GW level or for a customer limitation)
in_smpp_reject_diameter (smpp msg is rejected - reason: rejection by a diameter server - ChargingSbb !!!)
in_smpp_reject_mproc (smpp msg is rejected - reason: rejection by mprov rules)
in_smpp_drop_mproc (smpp msg is dropped (OK result was sent to a sender but a message is dropped) - reason: rejection by mprov rules)
in_smpp_error (a message receiving failed for other reasons)

in_http_received (a message is accepted from http connector)
in_http_reject_forbidden (http msg is rejected - reason: administrative reasons - SMSC is stopped or paused, cassandra database is not available, all messages from HTTP connector are forbidden)
in_http_reject_cong (http msg is rejected - reason: congestion at SMSC GW level or for a customer limitation)
in_http_reject_diameter (http msg is rejected - reason: rejection by a diameter server - ChargingSbb !!!)
in_http_reject_mproc  (http msg is rejected - reason: rejection by mprov rules)
in_http_drop_mproc (http msg is dropped (OK result was sent to a sender but a message is dropped) - reason: rejection by mprov rules)
in_http_error (a message receiving failed for other reasons)

b) “Out” (a result of message sending) - we cover only smpp side this step

out_smpp_sent (smpp: a message is successfully sent)
out_smpp_rejected (smpp: received non zero smpp response code when message sending)
out_smpp_error (smpp: error in a sending process for example a channel error)
out_smpp_timout (smpp: no response from a peer intime may be because of connection problems or peer malfunction, delivery timeout case included)
validiy_period_timeout (a message has not sent because of validity period timeout)

** ErrorCode:
From org.mobicents.smsc.library.ErrorCode.
We have error codes for all delivery parts. We need to add error codes for rejecting at an incoming step and internal rejecting by mproc rules (new values will be added from number 229).

** MessageType:
SubmitSm
SubmitMulti
DeliverSm
DataSm
Http

**  Timestamp A :
IN: The time the message is successfully decoded
OUT: The time the message is received for sending

**  Timestamp B :
IN: The timestamp taken immediately after sending of the response
OUT: Immediately after sending of the request

**  Timestamp C :
IN: The timestamp taken immediately after submission for further processing
OUT: the time the message response is successfully decoded

This cdr logging will be put in a separate file “*.dcdr”  (dcdr == detailed CDRs).
This logging is turned off by default. Configuring by:
GUI: “SMSC Gateway Server Settings - CDR - Generate detailed CDRs“
CLI: smsc set generateredcdr false

Testing: 
Testing of a live system  - checking generated CDRs for _ALL_ described before cases including of checking values of fields
performance testing to see the impact of counters and potentially batch on the CI env performance job

**Comment by vetss** [comment]
Hello @satanatoly 

I have a short look for https://github.com/satanatoly/smscgateway/commit/2833df266f43fe6225936c537967124eb9a66845

My comments:
- I do not see you save timestamps A-C from anythere from code, so I think you have not finished of implementing, do you use also all needed fields like IP addresses etc ?
- IMHO timestamps A-C are not needed to save into a database because they will be used before string of a message into a database.
- code style - we need to remove extra unused "imports"
- we need to store detailed CDRc into a special separate file and for this we need to update jboss-log4j.xml config file (and templates for it inside SMSC GW project)

**Comment by satanatoly** [comment]
Fixed by:
187f336b9d47ea8bc4ca6e1cedcee3126632e2a4
cd6f53c81cfc617463066e9d78b9f86b4177c629
119f48cd8a90d2bddcc0dc99e6ea709abecbf747
af21529ba772f767df10bb9f25b91f89eec8f7b1
600bd656214cba95058209babe8fdfaf2f3ba272
fa71dad2cd8479d970deba6ee37e3a2c093a61a4
438997ca1de5622bd4e01c31f9e186f8e8b7440e
7a46aa8ddd42a76b62fc1daefc29d2021f8bfafa
cb22b36577ba39c937f4b3474eca793b12e2f3f1
c803d75c76a1eb1c974ba82daa7b2d934809d57d
10dafc44a629514920326fbd84f2a3b75bb81d64
f83724758bad61c7fa27fa26fc6d314f9c47c6bb

**Comment by satanatoly** [comment]
Fixed by:
187f336b9d47ea8bc4ca6e1cedcee3126632e2a4
cd6f53c81cfc617463066e9d78b9f86b4177c629
119f48cd8a90d2bddcc0dc99e6ea709abecbf747
af21529ba772f767df10bb9f25b91f89eec8f7b1
600bd656214cba95058209babe8fdfaf2f3ba272
fa71dad2cd8479d970deba6ee37e3a2c093a61a4
438997ca1de5622bd4e01c31f9e186f8e8b7440e
7a46aa8ddd42a76b62fc1daefc29d2021f8bfafa
cb22b36577ba39c937f4b3474eca793b12e2f3f1
c803d75c76a1eb1c974ba82daa7b2d934809d57d
10dafc44a629514920326fbd84f2a3b75bb81d64
f83724758bad61c7fa27fa26fc6d314f9c47c6bb
e0537f460728c7a5bb46d05d0895173fcdf46977
9bbaa4d9205acfd873bfae3e69af891c674bc605
6afe68a952af177dba2b2bb7a545fb99351ec6cf
507acf0fa7bc7e7687672a7a384f9c48eed22dc5
