### ISSUE TITLE
CDR field Delivery Receipt - new fields

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#218]
This is a list of requested new CDR fields to the main CDR records.

1) "DeliveryReceiptMessageStatus"
- if DLR is parsed - value of the field "Stat" of a message body
2) "DeliveryReceiptMessageStateTlv"
- if DLR is parsed and we have TLV "Message State" (tag 0x0427) - value of this TLV
3) "DeliveryReceiptMessageErr"
- if DLR is parsed - value of the field "Err" of a message body

Testing:
Make a live SMSC GW testing of filling of such values.

**Comment by satanatoly** [comment]
Fixed by:
c44b58208df2a61bacf53fda8c07b4d476606d17
b99f2df4af7fba1014d1169499ad3740057ea8d4
fca4b51f236bd1d37d6c9536179722b9a49c2ef6

**Comment by satanatoly** [comment]
Fixed by:
c44b58208df2a61bacf53fda8c07b4d476606d17
b99f2df4af7fba1014d1169499ad3740057ea8d4
fca4b51f236bd1d37d6c9536179722b9a49c2ef6
5096db08b2b9a343a6239a3a9095e1ace6166603
