### ISSUE TITLE
ENQUIRE messages also for SERVER type ESMEs

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#22]
We have the following functionality for CLIENT type ESMEs:
a possibility of sending periodically ENQUIRE messages to a peer and if 3 responses was not achieved back - SMSC GW will break a connection.

We need to make the same for SERVER type ESMEs. This option must be configurable (turnung on/off and sending intervals).

**Comment by nhanth87** [comment]
Hi @vetss, @abhayani : We have two options for enhancing this issue:
1. duplicate SmppClientOpsThread.java to  SmppServerOpsThread.java, it's fas
2. rename SmppClientOpsThread.java to SmppOpsThread.java and do modify for both Server and Client. It's require more codes and tests to make sure the old behavious work correctly

Wdyt?
TN

**Comment by vetss** [comment]
We can make both solutions.
I'd prefer to have some super class like SmppOpsThread that implements low level logic and two subclasses for a server and a client. Only Client class will care of reconnection.

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/9056810e2f167b1c4884e538457123f77b8a9c1d
https://github.com/RestComm/smscgateway/commit/5331952e16d4522422b05eda234d09c43ebe2adb
https://github.com/RestComm/smscgateway/commit/fe882115ef6b9d875fa93a2c60c3f38a368f2e7b
https://github.com/RestComm/smscgateway/commit/9a5598e27659fe388b71c861d233c5c7017347e3
