### ISSUE TITLE
mproc rules: adding drop / reject actions

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#227]
We need to add 2 actions for mproc rules:

1) dropOnArrival true|false  - lead PostArrivalProcessor.dropMessage() if "true" (false == disabling)
2) rejectOnArrival none | default | unexpectedDataValue | systemFailure | throttling | facilityNotSupported  - leads:

- none - turn off of the action
- default - PostArrivalProcessor.rejectMessage()
- <other values> - PostArrivalProcessor.rejectMessage(int anSmppErrorCode, int aMapErrorCode, int aHttpErrorCode)

Meaning of "dropOnArrival" - message will be dropped but a sender receives a success response
Meaning of "rejectOnArrival" - message will be dropped but a sender receives an error response

Values for "reject"
unexpectedDataValue:
- SS7: 36 (unexpectedDataValue)
- SMPP: 0x15 (Invalid service type)
- HTTP: 2
- SIP (we return succes as for now)

systemFailure:
- SS7: 34 (systemFailure)
- SMPP: 0x8 (System error)
- HTTP: 3
- SIP (we return succes as for now)

throttling:
- SS7: 51 (resoureLimitation)
- SMPP: 0x58 (Throttling error)
- HTTP: 4
- SIP (we return succes as for now)

facilityNotSupported:
- SS7: 21 (facilityNotSupported)
- SMPP: 0x65 (Permanent application error)
- HTTP: 5
- SIP (we return succes as for now)

default (only for info, we reuse a method without parameters):
- SS7: 34 (systemFailure)
- SMPP: 0 (Success)
- HTTP: 1
- SIP (we return succes as for now)

**Comment by vetss** [comment]
Partly fixed by:

https://github.com/RestComm/smscgateway/commit/7fa889de8bfb5d80bf4041d9a575c4444b14ed66

**Comment by vetss** [comment]
Hello @satanatoly 

I agree with functionality implementation but I have one remark for configuring of "Reject upon arrival to the server".

1) At the creating rule part (GUI) you allow "" and "NONE" values for "no reject action".
And I do not see how can I remove the option in the rule update. I can configure "NONE" but this "NONE" value will still present in xml config (the proper behaviour is when we turn off the option then no option mentioning in xml config / CLI show commans - else we will have bery unclear to read)

I suggest that for both null / NONE option we will not have write data into xml / show in CLI.

2) GUI edit part HELP must contain a list of possible values - check "Destination Type Of Number (TON)" help for example.

**Comment by satanatoly** [comment]
Fixed by:
7fa889de8bfb5d80bf4041d9a575c4444b14ed66
75da1286dd9a5fc3cb27b4bdb6be080cb9794dcb
