### ISSUE TITLE
submit_sm_resp contains a filled "message_id" field - must be null

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#232]
As for spec "delivery_sm_resp" must contain null value in a "message_id" field (as for spec). We are filling it now.

This does not affect responses of submit_sm, submit_sm_multi, data_sm (only delivery_sm).

**Comment by faizann** [comment]
Hi

I find this change strange. The messageId is used in DeliverSm to match the original SubmitSm by the SMPP client. If we send NULL in the SubmitSmResp, won't this will break a lot of SMPP clients?
A typical DLR message body looks like this where ID is the messageId.

`short_message="id:34265880701 sub:001 dlvrd:001 submit date:1709260755 done date:1709260755 stat:UNDELIV err:001 text:sfdsfs`

**Comment by faizann** [comment]
Deleted the comment by mistake. 
Don't we need the messageID to link to the DeliveryReport? If it is set to null that will break the delivery reports.

**Comment by vetss** [comment]
Hello @faizann 

ohh, correct, my bad. "delivery_sm_resp" must contain null value in a "message_id".
We need to update it.

**Comment by olenara** [comment]
Fixed by:
ebd835e804413786dbdce10107edb5f082837afe
3aee28518a3d2461bba040c02783f0cc47418297

**Comment by olenara** [comment]
Code has been merged to master.
