### ISSUE TITLE
ai=83 while ssn=0 

### ISSUE THREAD

**Issue by almayeen** [RestComm/smscgateway#235]
Dears 

I think ai must be 81 when ssn=0, the web interface also refused setting ai=83 when ssn=0.

Please check sccp address configuration in
core/bootstrap/src/main/config/data/SccpStack_sccprouter2.xml

<id value="1"/>
	<sccpAddress pc="1" ssn="0">
 		<ai value="83"/>
 		<gt type="GT0100" tt="0" es="1" np="1" nai="4" digits="000"/>
 	</sccpAddress>

Regards

**Comment by vetss** [comment]
Hello @almayeen 

if you read in http://documentation.telestax.com/core/ss7/SS7_Stack_User_Guide.html#_managing_sccp
a description for <address-indicator> field for "sccp address modify" :

```
Only two fields of Address Indicator is used now for GTT:
                    - GT Indicator (this is used for GlobalTitle type that
                      will be created)
                    - Routing Indicator bit (0 = Route on GT, 1 = Route on
                      PC + SSN)
                    GT Indicator for ITU-T network that is mostly used is -
                    0100 (GT includes Translation Type, Numbering Plan and
                    Encoding Scheme and Nature of Address). Digital value
                    for it is - 16.
                    For 0100 GT Indicator we will use two possible values:
                    16 - 0100 GT Indicator and Route on GT
                    80 - 0100 GT Indicator and Route on PC + SSN
                    Even when SCCP stack works in ANSI mode Address Indicator
                    value for CLI and GUI must have values that we use for
                    ITU-T mode.
```

then you find that "SSN indicator" bit does not affect, so value "80" is also possible. SSN will be transmitten in any case.

**Comment by almayeen** [comment]
Thanks @vetss for your reply and details, it's clear to me now.
