### ISSUE TITLE
CDR counter - MessagePartProcessingTime

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#238]
We need to add a new counter into a CDR that will calculate a processing time between a previous message part delivering and a current message part delivering for messages that are split by SMSC GW at the sending time.

For non-split by SMSC GW messages and for a first part of a split message this counter will have a same behaviour as a "processing time" counter.

**Comment by ovoo-unif** [comment]
Hi Sergey,

if we cannot make use of requestEstimatedProcessingTime from cloudhopper-smpp class ConcurrentCommandCounter - then OK.

It is not perfect/ideal solution. Go for it if you don't see other reasonable possibility.

Regards,
adam

**Comment by vetss** [comment]
Hello Adam,

I do not think we can use requestEstimatedProcessingTime.

**Comment by vetss** [comment]
- The idea is to CDR into a new counter value of time "between previous segment delivery time and next segement delivery time". For a first segment (no previous segement) this counter will have a same behaviour as a "processing time" counter.
Say this is time between two CDR records (for previous segment / current). You implemented time storing into SMS class (sms.putMsgPartDeliveryTime(sentSequenceNumber, t);)
when message splitting for RxSmpp (MT more or less ok). This is a demand of a customer.
- I think better to change "HashMap<Integer, Long> msgPartsDeliveryTime -> Long Sms.msgPartsDeliveryTime" and put there a single value (not an array for each segment). We are sending a segment one by one and a single value is good enough.
- Store sms.putMsgPartDeliveryTime() when storing of a CDR of a segment. When writing a CDR if msgPartsDeliveryTime is null then it means the first segment - we reuse "processing time" for the new counter

**Comment by olenara** [comment]
Code has been merged to master.
