### ISSUE TITLE
RestComm smscgateway Development Setup Guide - MISSING

### ISSUE THREAD

**Issue by alamsher** [RestComm/smscgateway#244]
Hello, 

Is there any Development Setup Guide for RestComm smscgateway? 
Idea is to be able to configure the project in some IDE and then make code changes that are hot deployable and testable. 

However, after checking a lot online, I could not find a single documentation providing the related info. 
Kindly guide. 

Thanks

**Comment by vetss** [comment]
The only manual we have is here
http://documentation.telestax.com/core/smsc/SMSC_Gateway_Installation_Guide.html
http://documentation.telestax.com/core/smsc/SMSC_Gateway_Admin_Guide.html

**Comment by olenara** [comment]
Please let us know if you have further questions.
