### ISSUE TITLE
remove SMS's non printable in server.log

### ISSUE THREAD

**Issue by nhanth87** [RestComm/smscgateway#250]
Nonprintable characters make line break in server.log
they make log monitoring and parser more difficult.
We can consider to remove them when logging to server.log

Follow zendesk 34607

Br,
TN

**Comment by nhanth87** [comment]
remove nonprintable character require checking every character in the SMS body, it will make highload

**Comment by vetss** [comment]
We have many such logging records. Better to point concrete examples that we need to update if we know such examples.

**Comment by nhanth87** [comment]
It's a code that caught line break (because of \n)

			logger.severe(String.format("\nonPduRequestTimeout : targetId=" + smsSet.getTargetId()
                    + ", PduRequestTimeout=" + event));

**Comment by KeithMilner** [comment]
I have examples of this from binary messages, for example, from cdr.log:
2017-09-14 16:07:11,700 DEBUG [org.mobicents.smsc.library.CdrGenerator] 2017-09-14 16:07:11.544,447440905420,1,1,17632400099,1,1,success_esme,SMPP,message,gateway1,3346224,,null,null,null,null,null,null,2,6,null,0,0,,,,,"*5*I▒1dL
                                                                                             ▒0`@I",""
A good approach would seem to be to wrap the output with a function which strips out non-printable characters. There are some examples at https://stackoverflow.com/questions/6198986/how-can-i-replace-non-printable-unicode-characters-in-java

**Comment by olenara** [comment]
Fixed by:
2dcb45ddc5a7f9cbf85258a5ff80ebd468ae874e
c102fc9b69350dc4e042ef5cf55a1e2449cd3eaf
