### ISSUE TITLE
Character 0x00 in concatenated SMS causes SMSC to think message is too long

### ISSUE THREAD

**Issue by KeithMilner** [RestComm/smscgateway#253]
If a concatenated message is sent via SMPP which includes the character 0x00 in any of the intermediate parts, this causes the SMSC to interpret that part as being too long, returning a message:

> Message length in bytes is too big for solid message: 135>134

It does this even when the message length is correct (153 characters using GSM7 encoding).

Although character code 0x00 is probably not a useful character in a text message, it may appear by accident in which case it should probably be ignored rather than cause a problem. I've not checked this with other ASCII control characters.

**Comment by KeithMilner** [comment]
Attached ZIP showing pcap example.
[smpp20_anon.pcapng.zip](https://github.com/RestComm/smscgateway/files/1306995/smpp20_anon.pcapng.zip)

**Comment by vetss** [comment]
Hello @KeithMilner 

"153 bytes using GSM7 encoding" - I think you mean "153 septets" when for bytes more correct "135 bytes" (and 6 bytes for UDH), am I correct ?

"it should probably be ignored rather than cause a problem" - please explain which behaviour you mean is proper. Do you agree that when we do byte to byte encoding (including 0x00 char) + UDH we will have > 140 bytes ? If not please let me know we need to make test encoding then. If yes then what SMSC GW should do in encoding process ?

This is my unit test which I used for checking of message length in bytes after encoding:

        DataCodingScheme dcs = new DataCodingSchemeImpl(0);
        String msg = "ssage part is too long by one character.\nWe will now insert the character here ->\0 and this should cause the error to occur. However, we need to make sur";
        UserDataHeader udh = new UserDataHeaderImpl();
        ConcatenatedShortMessagesIdentifierImpl udhe = new ConcatenatedShortMessagesIdentifierImpl(false, 122, 5, 3);
        udh.addInformationElement(udhe);
        int messageLen = MessageUtil.getMessageLengthInBytes(dcs, msg, udh);

messageLen==135 after it.

**Comment by KeithMilner** [comment]
@vetss yes, indeed, I don't mean 153 bytes. I have corrected the comment above to read 153 _characters_.

I believe the UDH is 5 bytes (it is in the packet captures I have taken).

At the moment, the issue is, when the message payload is at maximum size, if the character 0x00 is present it seems to result in the payload size increasing by one. As per your test, it results in a messageLen of 135 which is too large and causes the message to fail.

My understanding is that the character 0x00 is resulting in the message length after encoding becoming one byte larger than if the 0x00 character is replaced by another standard character. So, for instance, if you use the line:
String msg = "ssage part is too long by one character.\nWe will now insert the character here ->X and this should cause the error to occur. However, we need to make sur";

in the above code, then messageLen should be 134 characters.

I've attached a zip with some additional packet captures of this concatenated message with the character 0x00 and with an "X" character instead of the 0x00. The two have identical message sizes:

With 0x00:
0000   73 73 61 67 65 20 70 61 72 74 20 69 73 20 74 6f  ssage part is to
0010   6f 20 6c 6f 6e 67 20 62 79 20 6f 6e 65 20 63 68  o long by one ch
0020   61 72 61 63 74 65 72 2e 0a 57 65 20 77 69 6c 6c  aracter..We will
0030   20 6e 6f 77 20 69 6e 73 65 72 74 20 74 68 65 20   now insert the 
0040   63 68 61 72 61 63 74 65 72 20 68 65 72 65 20 2d  character here -
0050   3e **00** 20 61 6e 64 20 74 68 69 73 20 73 68 6f 75  >. and this shou
0060   6c 64 20 63 61 75 73 65 20 74 68 65 20 65 72 72  ld cause the err
0070   6f 72 20 74 6f 20 6f 63 63 75 72 2e 20 48 6f 77  or to occur. How
0080   65 76 65 72 2c 20 77 65 20 6e 65 65 64 20 74 6f  ever, we need to
0090   20 6d 61 6b 65 20 73 75 72                        make sur

Without 0x00:
0000   73 73 61 67 65 20 70 61 72 74 20 69 73 20 74 6f  ssage part is to
0010   6f 20 6c 6f 6e 67 20 62 79 20 6f 6e 65 20 63 68  o long by one ch
0020   61 72 61 63 74 65 72 2e 0a 57 65 20 77 69 6c 6c  aracter..We will
0030   20 6e 6f 77 20 69 6e 73 65 72 74 20 74 68 65 20   now insert the 
0040   63 68 61 72 61 63 74 65 72 20 68 65 72 65 20 2d  character here -
0050   3e **58** 20 61 6e 64 20 74 68 69 73 20 73 68 6f 75  >X and this shou
0060   6c 64 20 63 61 75 73 65 20 74 68 65 20 65 72 72  ld cause the err
0070   6f 72 20 74 6f 20 6f 63 63 75 72 2e 20 48 6f 77  or to occur. How
0080   65 76 65 72 2c 20 77 65 20 6e 65 65 64 20 74 6f  ever, we need to
0090   20 6d 61 6b 65 20 73 75 72                        make sur

But in the case where 0x00 is present, the messageLen is computed to be 135 bytes instead of 134.

In the packet captures, compare packet number 14 in the two files.

[PacketCaptures.zip](https://github.com/RestComm/smscgateway/files/1307735/PacketCaptures.zip)

**Comment by vetss** [comment]
Hello @KeithMilner 

> But in the case where 0x00 is present, the messageLen is computed to be 135 bytes instead of 134.

Yes I see it, we may treat it as a bug, and we can fix it (calculate 0x00 char as a single character). I have one question - how do you mean we need to uncode it at GSM part ? As a space (' ') ?

**Comment by KeithMilner** [comment]
@vetss  A space makes most sense to me.

Just to be clear, I have "SMPP coding for GSM7" set to UTF8. In UTF8, of course, the code for 0x00 is "NUL".

Of course that is a valid character in many contexts, but it isn't a printable character in the context of SMS. In that case it seems to make sense to either display a space or omit it completely. In some respects omitting it completely would be preferable but, depending on the implementation, it may also change the length of the message part, which may cause complications.

The easiest approach would be to replace the 0x00 (and any other non-functional characters) and replace with a space before the calculation of the size is done.

I noticed that the computation of this involves use of the GSM Character set classes from jSS7. I've not examined this code, but I wonder if there is a bug within that class?

**Comment by vetss** [comment]
Yes, it is JSS7 part issue: https://github.com/RestComm/jss7/issues/263

@KeithMilner thanks for bug reporting.

**Comment by olenara** [comment]
Fixed by https://github.com/RestComm/jss7/commit/d7ee8c3d2eb441c3630aa0c8625479651604d80a
