### ISSUE TITLE
Mark equipmentProtocolError as a permanent failure

### ISSUE THREAD

**Issue by marca56** [RestComm/smscgateway#254]
* see, customer change request in the Slack channel

**Comment by vetss** [comment]
Way of implementing:

1) we need to implement https://github.com/RestComm/jss7/issues/264

2) Add following configuring parameters:
a) smsc set smdeliveryfailure <csuaseCode> permanent/temporary/clear
examples:
smsc set smdeliveryfailure 0 temparary - set MAPErrorMessageSMDeliveryFailure error FailureCause 0 (memoryCapacityExceeded) to temparary
smsc set smdeliveryfailure 1 permanent - set MAPErrorMessageSMDeliveryFailure error FailureCause  1 (equipmentProtocolError) to permanent
smsc set smdeliveryfailure 2 clear - set MAPErrorMessageSMDeliveryFailure error FailureCause  2 (equipmentNotSMEquipped) to a default SMSC GW value

**Comment by vetss** [comment]
3. Changing of SMSC GW behaviour:

a) SMEnumeratedDeliveryFailureCause - equipmentProtocolError - treat this error as permament as default (we will treat as temporary by default only memoryCapacityExceeded case) 

b) when parsing of MAPErrorMessageSMDeliveryFailure MAP erro message:
- If signallingInfo + SMS-DELIVERY-REPORT + TP-Failure-Cause is present we make a decision of temporary / permanemt error depending on smdeliveryfailure_tpfailurecause (if not specified - then an failure is permamant by default)
- If TP-Failure-Cause is absent we make a decision of temporary / permanemt error depending on smdeliveryfailure per SMEnumeratedDeliveryFailureCause (if not specified - then an failure is permamant by default except memoryCapacityExceeded that is temporary by default)

c) if an error is permanent and TO-User-Data is present then DLR content depends on smdeliveryfailure_dlr_withtpuserdata.

**Comment by nhanth87** [comment]
I have sent PR https://github.com/RestComm/smscgateway/pull/270
Tested at my side, testing on customer side

Br,
TN

**Comment by vetss** [comment]
I have added a litle update for:
https://github.com/RestComm/smscgateway/commit/c521fe98d916a1548963518f41382470959ef2ed

I still need an end-to-end testing
