### ISSUE TITLE
Non unique messageIDs between SMSCs cause conflict

### ISSUE THREAD

**Issue by faizann** [RestComm/smscgateway#256]
MessageID in SMSC is a sequential number and if there are 2 or more SMSCs instances running. The SMPP clients start receiving similar messageID for multiple submits and hence there is a conflict on DLR. A DLR from messageSent to SMSC_A might be thought of as DLR from SMSC_B.

I suggest using UUIDs for messageIDs to avoid conflicts when SMSCs are run in loadshare mode. It is a big change if we do it for the whole SMSC but we might be able to just do it for SMPP (and possibly SIP/HTTP) where DLRs are used.

**Comment by vetss** [comment]
Hello @faizann 

you can use "Minimum MessageId" and "maxMessageId" general SMSC GW options for setting of a range of messageID values in a server - check http://documentation.telestax.com/core/smsc/SMSC_Gateway_Admin_Guide.html#smsc-gateway-server-settings .

Usage of "UUIDs for messageIDs" demands a significant server update, let's rty to use the first option.

**Comment by faizann** [comment]
Hi

Ah I didn't see that. Using UUID would have broken the protocol anyway. Thanks. I don't need any changes then.
