### ISSUE TITLE
Unable to set  right bit sequence in Address Indicator (AI)  field of SCCP layer

### ISSUE THREAD

**Issue by Baymax254** [RestComm/smscgateway#263]
I want to route message on basis of PC+SSN, but when i set the bits of AI accordingly, it returns an error 'java.lang.NullPointerException'. For example, code doesn't allow me to set AI= 01010011 but when i set 7th bit to 0, such that AI= 01010001,  the value is accepted and address is added. Also, when the rule is added , the 7th bit appear as 1 instead, like AI= 01010011

**Comment by vetss** [comment]
Hello @Baymax254 

at which step do you have NullPointerException - at a sccp rule creation or when a mesageflow. If it is a first one, can you provide a CLI commant that gives you NullPointerException.

**Comment by Baymax254** [comment]
Hi vetss,

The error pops up at the time of rule is created via GUI.

**Comment by vetss** [comment]
Hello @Baymax254 

can you please provide which parameters you are using for creating of a SCCP rules (I suppose you are trying o create the rule). I can not reproduce a NullPointerException locally. The best if you can provide a CLI command but GUI settings are also good.

Please also check the manual - http://documentation.telestax.com/core/ss7/SS7_Stack_User_Guide.html#_managing_sccp the chapter that "7.4.17. Create a new SCCP Rule" and a chapter for SCCP address creating. These chapters contain the info which exactly AI bits are taken into account for SCCP message processing (not all bits are needed to be set).

**Comment by Baymax254** [comment]
Hi,


I am adding AI in the address field of SCCP layer, doing it via GUI. I have
made a demonstration of my issue in the form of slides. Kindly ack. PFA

**Comment by vetss** [comment]
Hello @Baymax254 

how can I see "a demonstration of my issue in the form of slides" ?

**Comment by Baymax254** [comment]
Here's a link [https://imgur.com/a/rP4ft](url)

**Comment by Baymax254** [comment]
Here's a link https://imgur.com/a/rP4ft

**Comment by vetss** [comment]
@Baymax254 

ok, I understand your mistake - use "83" value for "AddressIndicator" field instead of "01010011". It is a decimal value.

**Comment by Baymax254** [comment]
Thanks. I will try it.
