### ISSUE TITLE
Skipping of SRI in case IMSI/VMSC is known

### ISSUE THREAD

**Issue by faizann** [RestComm/smscgateway#265]
In some special cases of M2M messaging the IMSI and VMSC is already known. This means that SRI is not needed and simply MTFSM can be sent. 
I would like to suggest a change where MProc can set the IMSI/VMSC values in SmsSet object before SRI  (onPostArrival of SMPP or SIP) and SriSbb can just do executeForwardSM.

**Comment by vetss** [comment]
Hello @faizann 

thanks for raising an issue. I think we can not add a default mproc rule staff for that case because IMSI/NNN(VMSC) is needed to be taken from a database or another source like this. And we need to prepare custom mproc rules for it.

Can you contribute this staff ?

**Comment by faizann** [comment]
Yeah so that will be OnPreSriRequest type of MProc. Makes sense.

Thanks

**Comment by nhanth87** [comment]
it's implemented in SMSC onpremise version so I close this
