### ISSUE TITLE
AS not active issue in (manual) client-server connection 

### ISSUE THREAD

**Issue by Baymax254** [RestComm/smscgateway#266]
I have this issue since quite long. I configure (manually)  jSS7 stack via GUI and try to make a connection between smsc gateway and ss7 simulator. The connection set up successfully but i am unable to see HEARTBEAT packets between two entities (server: smsc gateway, client: jss7 simulator). Also, in alarms i get AS state not active. 
In Wireshark trace, I am able to get BEAT followed by SACK BEAT_ACK but not HEARTBEAT packets as observed in per-configured default setup that runs on local host. What could be the possible cause?

**Comment by nhanth87** [comment]
Hi,
Can you use https://groups.google.com/forum/#!forum/mobicents-public and stackoverflow for the question?

In github issue, we are using to keep track of development/bug fixing only

About your case, in the config file Mtp3UserPart_m3ua1.xml please change heartbeat from `false` to `true`

Br,
TN

**Comment by Baymax254** [comment]
Ok sure. I have set it true from GUI. thanks
