### ISSUE TITLE
Mproc rule: remove of an prefix from dest address digits

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#267]
We need to add an action into default mproc rules implementation:

"removedestdigprefix" <digits count>

This action will remove first <digits count> digits count from a dest address digits. The action will leave at least one (last) digit if <digits count> value is too long. Default value "0". values "0" and negative values will make no actions.
We need to update CLI / GUI / manual.

**Comment by scottbarstow** [comment]
@vetss i think we want more control than just "remove prefix." It needs to be flexible enough to support the following options:
- I want to remove the prefix (in our case +) when it's +1 but leave the + if it's +(anythingelse)
- I want to remove the prefix in all cases

questions / comments?

**Comment by vetss** [comment]
Hello @scottbarstow 

We will use this action with other existing functionality - conditions.
Example (we will remove one leading sign if oigina ESME name matches to `^(test)$` and a dest address digits match to mask `<mask for processing>`) :

```
smsc mproc add mproc 1 destdigmask <mask for processing> origesmenamemask ^(test)$ removedestdigprefix 1
```

**Comment by olenara** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/1f70a2c6e090bcab7cc7d6a9b52079343f4f75fe
https://github.com/RestComm/smscgateway/commit/0aed184f1e4bd9500c89ba0cb90792a2d9a1a4a7
https://github.com/RestComm/smscgateway/commit/5c63e10e80a01664467f608674f6e8e57605b268
