### ISSUE TITLE
mechanism for removing SMS in Cassandra database

### ISSUE THREAD

**Issue by nhanth87** [RestComm/smscgateway#269]
From ticket 34617.
If:
1. Send SMS from 1 ESME to another ESME (2nd)
2. 2nd ESME is not BOUND so SMSC will setup SMS for retry
3. Before retry timeout, delete the ESME from SMPP Management console

Then SMS will be stuck in database because SMSC don't have mechanism to remove the SMS related to unavailable ESME (SMSC don't know the difference between ESME stopped or unavailabled)

Br,
TN

**Comment by olenara** [comment]
Issue has been resolved by fff53088a569fc18cb1510f7acd1e2ea848ab796 commit in commercial release. Related jira MSB-168.
