### ISSUE TITLE
Not all SBBs are running?

### ISSUE THREAD

**Issue by MaabSaleeem** [RestComm/smscgateway#279]
Why does this warning come and what does this affect?

17:11:47,639 INFO  [SchedulerResourceAdaptor] (pool-50-thread-1) Not all SBB are running now: ServicesDownList=[smscTxSmppServerServiceState, smscRxSmppServerServiceState, smscTxSipServerServiceState, smscRxSipServerServiceState, smscTxHttpServerServiceState, moServiceState, homeRoutingServiceState, mtServiceState, alertServiceState, chargingServiceState, ]

**Comment by gsaslis** [comment]
@MaabSaleeem can you please share some more information about the circumstances in which this log message comes up?

It would be really helpful if you could provide steps to reproduce and some more complete logs (using [GitHubGist](https://gist.github.com/) ), so we can take a closer look.

Thanks in advance!

(btw, I see this is only `INFO` level...? )

**Comment by olenara** [comment]
@MaabSaleeem there must be errors that precedes this one, which were the reason for SBBs not to start. In your case, considering another issue you've opened (https://github.com/RestComm/smscgateway/issues/278) it must be a correct version of Java (should be 7).

**Comment by princebayan** [comment]
@MaabSaleeem its a Java version issue, same was happening with me when i run Jboss on Java 8.

**Comment by MaabSaleeem** [comment]
@princebayan which version did you then shift to?

**Comment by princebayan** [comment]
@MaabSaleeem I switch to version 7 and exactly this one : java version "1.7.0_181".
Try it and if you need anything please tell me.

**Comment by MaabSaleeem** [comment]
@princebayan Thanks. If I need anything else, I can reach you at prince_bayan@hotmail.com?

**Comment by princebayan** [comment]
yes sure :)
