### ISSUE TITLE
MAP Error msg: facilitynotsup

### ISSUE THREAD

**Issue by terminator102** [RestComm/smscgateway#281]
Whenever SMSC receives msg from remote SMSC, it returns following error:

Home routing: Sent ErrorComponent = MAPErrorMessageFacilityNotSup []

why is this? I am running old setup which was working fine few days back.

**Comment by nhanth87** [comment]
Check the cassandra database

**Comment by olenara** [comment]
@terminator102 you have to enable HrCharging SMSC property in configuration settings (set to to "accept").
