### ISSUE TITLE
Message sending failed from jss7-simulator to JITSI

### ISSUE THREAD

**Issue by Kawish-Ali** [RestComm/smscgateway#282]
While sending message from jss7-simulator to jitsi and using OpenJDK version 1.8 on kali linux following errors are occurs at 

**jss7- simulator:**

refuseReason=ApplicationContextNotSupported, alternativeApplicationContext=ApplicationContextName[oid=[0, 4, 0, 0, 1, 0, 21, 3]], dlgId=1
257660 [pool-10-thread-1] INFO org.mobicents.protocols.ss7.tools.simulator.management.TesterHost  - Rcvd: DialogReject
refuseReason=ApplicationContextNotSupported, alternativeApplicationContext=ApplicationContextName[oid=[0, 4, 0, 0, 1, 0, 21, 3]], dlgId=1

**jboss 5.1.0.GA:**

05:02:41,802 INFO  [SelectorThread] (Thread-17) Connected Association [name=ass1, associationType=SERVER, ipChannelType=SCTP, hostAddress=, hostPort=0, peerAddress=127.0.0.1, peerPort=8011, serverName=serv1, extraHostAddress=[]]
05:02:41,848 INFO  [AssociationHandler] (Thread-17) New association setup for Association=ass1 with 10 outbound streams, and 32 inbound streams.

05:02:41,922 WARN  [SccpStackImpl-SccpStack] (pool-35-thread-1) Rx : MTP-RESUME: AffectedDpc=1
05:06:24,460 WARN  [MAPStackImpl-MapStack] (pool-28-thread-1) ApplicationContextName of non activated MAPService is received. Will send back TCAP Abort : 0, 4, 0, 0, 1, 0, 21, 3,

## The jss7-simulator successfully send the message to jboss but the jboss donot forward it JITSI...

**Comment by vetss** [comment]
Hello @Kawish-Ali 

> refuseReason=ApplicationContextNotSupported, 

This most probably mean that a ss7 stack / RAs are not properly started at jboss side

**Comment by olenara** [comment]
@Kawish-Ali if you still have questions, please provide SMSC startup logs that precedes this error.
