### ISSUE TITLE
How to start smsc gateway

### ISSUE THREAD

**Issue by cvmathur** [RestComm/smscgateway#284]
Hi guys,
I'm new to Java world and wanted to have an SMSC. I have followed the steps to build and install it.
By the end of it, I get the following message - 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] RestComm SMSC :: restcomm-smsc-parent .............. SUCCESS [ 36.473 s]
[INFO] Core ............................................... SUCCESS [  0.144 s]
[INFO] Core : MPROC API ................................... SUCCESS [02:40 min]
[INFO] Core : SMSC common Library ......................... SUCCESS [ 50.368 s]
[INFO] Core : Operations and Management : CLI ............. SUCCESS [ 19.948 s]
[INFO] Core : Domain ...................................... SUCCESS [02:07 min]
[INFO] Core : SLEE ........................................ SUCCESS [  0.006 s]
[INFO] Core : SLEE : Common Library ....................... SUCCESS [01:29 min]
[INFO] Core : SLEE : Persistence RA Parent ................ SUCCESS [  0.005 s]
[INFO] Core : SLEE : Persistence RA Library ............... SUCCESS [08:43 min]
[INFO] Core : SLEE : Persistence RA  Type ................. SUCCESS [  1.094 s]
[INFO] Core : SLEE : Persistence RA ....................... SUCCESS [ 29.027 s]
[INFO] Core : SLEE : Scheduler RA Parent .................. SUCCESS [  0.005 s]
[INFO] Core : SLEE : Scheduler RA Library ................. SUCCESS [  0.362 s]
[INFO] Core : SLEE : Scheduler RA Events .................. SUCCESS [  0.069 s]
[INFO] Core : SLEE : Scheduler RA  Type ................... SUCCESS [  0.497 s]
[INFO] Core : SLEE : Scheduler RA ......................... SUCCESS [  1.104 s]
[INFO] Core : SLEE : MProc RA Parent ...................... SUCCESS [  0.005 s]
[INFO] Core : SLEE : MProc RA Type ........................ SUCCESS [  0.403 s]
[INFO] Core : SLEE : MProc RA ............................. SUCCESS [  0.506 s]
[INFO] Core : SLEE : MProc RA Type : DU ................... SUCCESS [  8.562 s]
[INFO] Core : SLEE : MProc RA : DU ........................ SUCCESS [  0.220 s]
[INFO] Core : SLEE : SMSC Resource Adaptors DU ............ SUCCESS [  0.617 s]
[INFO] Core : SLEE ........................................ SUCCESS [  0.006 s]
[INFO] Core : SLEE : Services Parent ...................... SUCCESS [  0.005 s]
[INFO] Core : SLEE : Library .............................. SUCCESS [ 39.284 s]
[INFO] Core : SLEE : Services Alert SBB ................... SUCCESS [  6.358 s]
[INFO] Core : SLEE : Services Charging SBB ................ SUCCESS [  2.814 s]
[INFO] Core : SLEE : Services Sbbs ........................ SUCCESS [01:05 min]
[INFO] Core : SLEE : Services Tx SMPP Server SBB .......... SUCCESS [ 23.059 s]
[INFO] Core : SLEE : Services Tx HTTP Server SBB .......... SUCCESS [01:26 min]
[INFO] Core : SLEE : Services Tx SIP Server SBB ........... SUCCESS [  1.525 s]
[INFO] Core : SLEE : Services Mo SBB ...................... SUCCESS [ 14.579 s]
[INFO] Core : SLEE : Services Rx SMPP Server SBB .......... SUCCESS [ 19.005 s]
[INFO] Core : SLEE : Services Rx SIP Server SBB ........... SUCCESS [  1.405 s]
[INFO] Core : SLEE : Services Mt SBB ...................... SUCCESS [ 56.336 s]
[INFO] Core : SLEE : Services Home Routing SBB ............ SUCCESS [  1.495 s]
[INFO] Core : SLEE : SMSC Services DU ..................... SUCCESS [  0.822 s]
[INFO] Core : Bootstrap ................................... SUCCESS [01:03 min]
[INFO] Core : Bootstrap-wildfly ........................... SUCCESS [01:23 min]
[INFO] Test ............................................... SUCCESS [ 12.001 s]
[INFO] Test : MapModule ................................... SUCCESS [  0.635 s]
[INFO] Test : Bootstrap ................................... SUCCESS [ 17.906 s]
[INFO] Test SMPP Load ..................................... SUCCESS [  7.029 s]
[INFO] http-load .......................................... SUCCESS [  0.057 s]
[INFO] RestComm SMSC :: Tools :: Parent ................... SUCCESS [  0.109 s]
[INFO] SMPP Simulator :: Parent ........................... SUCCESS [  0.030 s]
[INFO] RestComm SMPP Simulator :: Simulator ............... SUCCESS [  1.352 s]
[INFO] RestComm SMPP Simulator :: Simulator Bootstrap ..... SUCCESS [  5.024 s]
[INFO] SMPP StressTool :: Parent .......................... SUCCESS [  0.029 s]
[INFO] Cassandra StressTool :: StressTool ................. SUCCESS [  1.246 s]
[INFO] RestComm CDR Parser :: Parent ...................... SUCCESS [  0.005 s]
[INFO] RestComm CDR Parser :: CDR Parser .................. SUCCESS [  0.567 s]
[INFO] RestComm Cassandra tool :: Parent .................. SUCCESS [  0.029 s]
[INFO] RestComm Cassandra tool :: Tool .................... SUCCESS [  0.742 s]
[INFO] RestComm SMSC :: Management :: UI :: ui-management . SUCCESS [  7.217 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28:34 min
[INFO] Finished at: 2018-03-01T04:58:38+00:00
[INFO] Final Memory: 416M/881M
[INFO] ------------------------------------------------------------------------

So now, how do I get going with it ? How to start monitor etc. ?

I would be grateful if some helpful soul guide me on this.

Thanks

**Comment by gsaslis** [comment]
Hi @cvmathur !

Please follow the [SMSC Installation Guide](https://www.restcomm.com/docs/core/smsc/SMSC_Gateway_Installation_Guide.html#introduction) to get you going. 

I will be closing this issue for now, please feel free to raise another more specific issue if you run across any other problems.
