### ISSUE TITLE
Container providing a null PersistenceUnitRootUrl: discovery impossible

### ISSUE THREAD

**Issue by haiderkhalid123** [RestComm/smscgateway#287]
I am trying to compile and run smscgateway from master branch. After compilation, when i run the smsc by executing this command
`./run.sh -b 192.168.1.71 -c simulator`

jboss server runs with some errors. the first of these error is:

`21:11:42,886 ERROR [Ejb3Configuration] (SLEE-InternalDeployer-thread-1) Container is providing a null PersistenceUnitRootUrl: discovery impossible`

**Comment by vetss** [comment]
Hello @haiderkhalid123 

you can safely ignore this error message
