### ISSUE TITLE
Docker Image for SMSC

### ISSUE THREAD

**Issue by deruelle** [RestComm/smscgateway#53]
Model it similarly to https://github.com/RestComm/Restcomm-Docker and https://github.com/RestComm/load-balancer-docker

**Comment by deruelle** [comment]
https://github.com/RestComm/smscgateway-docker

**Comment by deruelle** [comment]
@faizann I was wondering if you were able to move forward on this ?

**Comment by nicosmaris** [comment]
Hi all,

I started this ticket, but I have two issues.

1. I am stuck at the java version.

https://travis-ci.org/nicosmaris/smscgateway-docker/builds/186688517

The artifact 7.2.107 has cassandra 3.9 which needs java 8 but the documentation talks about java 7.

http://documentation.telestax.com/core/smsc/SMSC_Gateway_Admin_Guide.html#_mobicents_smsc_overview

2. Should I download anything else apart from the artifact?

**Comment by nhanth87** [comment]
Hi @nicosmaris, you just need to download both JAVA version directory and set JAVA_HOME to 8 for cassandra, JAVA_HOME to 7 for smscgw, it should work

Br,
TN

**Comment by nicosmaris** [comment]
Thanks @nhanth87 I managed to have an SMSC container linked to a cassandra container.

Now I start jboss with 'run.sh -b 0.0.0.0 -c simulator' but my curl gets a 'Connection refused'. To troubleshoot this, should I start with the jboss logs? If yes, is there a specific log that I should check first?

https://travis-ci.org/nicosmaris/smscgateway-docker/builds/186840296

**Comment by nhanth87** [comment]
Hi @nicosmaris please check server.log and boot.log at <jboss>/server/simulator/log

Br,
TN

**Comment by nicosmaris** [comment]
After several changes now there is a case in which it works.

https://travis-ci.org/nicosmaris/smscgateway-docker/builds/187390941

However at jboss startup I get the following.

Failure of connecting to cassandra database. : host=127.0.0.1, port=9042. SMSC GW will work without database support

Is cassandra optional?

**Comment by nhanth87** [comment]
@nicosmaris Cassandra is must have, Cassandra need to be run before smsc start

Br,
TN

**Comment by nicosmaris** [comment]
Possible next steps after reviewing the following pull request are:

1. make a docker hub account with a DOCKER_USERNAME and a DOCKER_PASSWORD
2. make a free travis account restcomm, enable travis at each commit of smscgateway-docker and store those variables at travis UI as "environment variables"
3. 'docker push' command at .travis.yml

https://github.com/RestComm/smscgateway-docker/pull/1

https://travis-ci.org/nicosmaris/smscgateway-docker/builds/187788797
