### ISSUE TITLE
CLI: Removing Archive Table Names command invalid

### ISSUE THREAD

**Issue by FerUy** [RestComm/smscgateway#58]
Removing Archive Table Names command description results in an invalid command answer using the CLI. The nemesis of the command as described in the documentation is as follows:
Name
smsc set removingarchivetabledays
SYNOPSIS
smsc set removingarchivetabledays <value>

See attached image of command execution failure.
![smsc_set_removingarchivetabledays_invalid](https://cloud.githubusercontent.com/assets/14883482/13907285/a52652ce-eec9-11e5-8f82-3e823a9f9b5a.png)

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/18711412f16850e6821eff6430dd1bf84139f8da
