### ISSUE TITLE
CLI: documentation error for smsc set txsmppcharging

### ISSUE THREAD

**Issue by FerUy** [RestComm/smscgateway#59]
As per the admin guide, this command: smsc set txsmppcharging, accepts values that are incorrectly spelled (none | selected | all). Should be None | Selected | All.
See attached image of command execution for more detailed exposure of the issue.

![smsc_set_txsmppcharging_doc-error](https://cloud.githubusercontent.com/assets/14883482/13908844/9a967a02-eeea-11e5-9a12-f5fbffd3f47d.png)

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/18711412f16850e6821eff6430dd1bf84139f8da
