### ISSUE TITLE
CLI: documentation error for smsc set txsipcharging

### ISSUE THREAD

**Issue by FerUy** [RestComm/smscgateway#60]
As per the admin guide, this command: smsc set txsipcharging, accepts values that are incorrectly spelled (none | selected | all). Should be None | Selected | All.
See attached image of command execution for more detailed exposure of the issue.

![smsc_set_txsipcharging_doc-error](https://cloud.githubusercontent.com/assets/14883482/13908924/08e4f9c4-eeec-11e5-8fe9-3e9f2d5f70d5.png)

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/18711412f16850e6821eff6430dd1bf84139f8da
