### ISSUE TITLE
CLI: documentation error for SMPP Server settings

### ISSUE THREAD

**Issue by FerUy** [RestComm/smscgateway#65]
All documented commands are invalid as documented in attached image:
![image](https://cloud.githubusercontent.com/assets/14883482/14097765/ed4c4acc-f54a-11e5-9e9e-4b06b767b19e.png)

**Comment by vetss** [comment]
Fixing by:
https://github.com/RestComm/smscgateway/commit/971bd1ce5faa7dd07f9b61d4c7014e910c29fa64
