### ISSUE TITLE
TCAP Invoke Timeout defaults to hardcoded 30 seconds

### ISSUE THREAD

**Issue by faizann** [RestComm/smscgateway#66]
All the MapDialogs created by SMSC don't specify the TCAP dialog timeout and Map stack hence uses hardcoded 30/60 seconds based on API call. This means that TCAP dialog timeout settings of SMSC is always ignored. 
There are 2 solutions
1-- Remove hardcoded timeouts in MAP API while creating TCAPDialogs
2-- Use a configurable timeout value from SMSC configuration to specify timeouts for SMS invokes. This still means that systemwide dialogtimeout value will have to be always higher than smsinvoketimeout. 

For simplicity and more control my suggestion is 2nd option.

**Comment by nhanth87** [comment]
Hi,
You can change tcap invoke timeout by 
<jboss>/...../data/TcapStack_management.xml

Br,
TN

**Comment by faizann** [comment]
No this one has no effect on SMSC Invokes. map-api/impl hardcodes it to 30/60 seconds for Invoke. Hence whatever value you set in TcapStack_management.xml is not obeyed. DialogTimeout on the other hand works for this.

Reopen the issue?

**Comment by deruelle** [comment]
@faizann do you want to provide a fix and pull request for this ?

**Comment by faizann** [comment]
Yes I do. I have opted for adding extra config for SMSC itself for
InvokeTimeout.

**Comment by nhanth87** [comment]
Hi Faizann,
As I understand from your ideas were that you are trying to use customInvokedTimeout in MAP api and make it configuration in SMSC GW?

Br,
TN

**Comment by faizann** [comment]
Yes that is correct. The map-api supports providing it a
customInvokeTimeout but if not provided it takes hardcoded timeout. Hence,
I want to use that for SMS Map messages from SMSC and configurable via
SmscPropertiesManager.

**Comment by nhanth87** [comment]
Let me check the code,
I'm thinking that if we not use customInvokedTimeout then value of TCAP stack will jump into

Br,
TN

**Comment by nhanth87** [comment]
Hi Faizann,
Just check through the codes of map-ra and jss7.
In case of no customInvokedTimeout then value from TCAP stack will take action.

Can you point me to the code that you think MAP/TCAP hardcoded 30/60 secs?

Br,
TN

**Comment by faizann** [comment]
Hi
In JSS7 on this line you can see that if customInvoke is not given (i.e.,
-1) then it takes a hardcoded value of 60 seconds from a constant.
https://github.com/RestComm/jss7/blob/master/map/map-impl/src/main/java/org/mobicents/protocols/ss7/map/service/sms/MAPDialogSmsImpl.java#L328

**Comment by nhanth87** [comment]
Ok, then misunderstood here. Let me explain you when smsc use jss7:
 SMSC (and USSD, Camel GW..) don't directly use jss7.
These products use the jainslee resource adapter (map ra) and it read the InvokedTimeout in the TCAP stack defined in jboss-beans.xml

Br,
TN

**Comment by faizann** [comment]
Hi Tran HN

Lets take example of an SRI request. The SriSbb.java which is a part of
SMSC SLEE, directly uses MapDialog and calls the function
*addSendRoutingInfoForSMRequest* which is what I linked to in previous
email. Hence the timeout used is customInvokeTimeout or the hardcoded one.
I did step into the code while debugging and hence I realised this case as
I kept on seeing invokeTimeouts after 30 seconds for SRI.
Here is the link/code
https://github.com/RestComm/smscgateway/blob/master/core/slee/services/mtsbb/src/main/java/org/mobicents/smsc/slee/services/mt/SriSbb.java#L627

**Comment by nhanth87** [comment]
Hi Faizann,
Because SMSC GW is based on Jainslee so it will use jss7 through jss7-ra (map ra) like connect to http through http-ra, connect to sip through sip-ra.

Can you spend some time in Jainslee spec.

And easy for testing, just stop your SMSC GW, modify the value and re-run it with ss7-simulator.

From me it works as expected.

Br,
TN

**Comment by nhanth87** [comment]
May be @abhayani and @vetss can give some idea

**Comment by faizann** [comment]
Hi Tran

I have read SLEE a few times but I am just looking into the code and I can
see SriSbb.java or other SBBs in SMSC calling map-impl directly. My last
email shows the code that calls and gets called.

I am using ss7-simulator for it.
When you say it works for you? have you tested with InvokeTimeout. I must
reiterate that this happens for InvokeTimeout and not DialogTimeout. Hence
it is not easy to notice unless you get a TCAP dialog back after
InvokeTimeout of 30 seconds which is rare.

Thanks

**Comment by nhanth87** [comment]
Hi Faizann,
Just want to say with you that: yes, I have tested it at my side and recommend many people change it and thus there's no comment from them.

Just don't want you to spend many time in case it's invalid. I will check the code of MAP-RA again and give feedback

Br,
TN

**Comment by vetss** [comment]
1) DialogTimeout can be set by this CLI command
tcap set dialogidletimeout <dialogidletimeout>

2) InvokeTimeout case is moer complicated. If you mean TCAP command
tcap set invoketimeout <invoketimeout>
then this valuse is not used at MAP stack. This is some sort of default value if the upper stack (MAP stack in our case) does not overwrite it.
MAP stack (unlike pure TCAP stack) has predefined timer values, see 
org.mobicents.protocols.ss7.map.api.MAPDialog:
    int _Timer_s = 10000;
    int _Timer_m = 30000;
    int _Timer_ml = 600000;
    int _Timer_l = 136800000;
for different Invoke types.
If we really need it, we need to provide configurable values for MAP (and CAP stacks) for different Invoke types. I think we do not need to fix it at SMSC GW or other high level application.
If you need it, feel free to open a separate issue in https://github.com/RestComm/jss7/issues

May I also ask WHY do you really need it ? In which real case do you face soem issues in this ? Do you need to increase or decrease values ?

**Comment by faizann** [comment]
Hi Sergey

In my test case a provider was sending back SRI response after 30 seconds
which caused UnrecognizedInvokeId and hence I saw a need for setting invoke
timeout for Sri larger than 30 secs.
MAP is indeed a better place for such timeout configurations.

**Comment by vetss** [comment]
1) I have created an issue for configuring of InvokeTimeout at MAP stack:
https://github.com/RestComm/jss7/issues/66

2) "timeout for Sri larger than 30 secs." usually mean that you have some overflowing in sending / receiving messages, then messages are buffered and do not delivering in time.

I am closing this ticket
