### ISSUE TITLE
Switching to Javolution 6.1

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#69]
We have some issues in Javolution 5.5.1 - xml part of it does not properly decode "\n" characters inside a String value: (decimal values like are processed well).

Javolution 6.1 is patched for it. But starting from version 6.0 it has different API interface and swithcing to this version needs the major code update. FastMap is replaced to other class(es) and XML part is also changed. We need to switch to all GWs at the single step because we can not use at the same server both Javolution 5.5 and 6.1.

Before this we need to fix the issue: RestComm/jss7#61

**Comment by olenara** [comment]
Won't do. Stable Javolution version 6.x.x or 7.x.x does not exist. Latest released version has bug which prevents to load config
