### ISSUE TITLE
SLEE Transaction not started exception in SchedulerRa

### ISSUE THREAD

**Issue by faizann** [RestComm/smscgateway#71]
File: SchedulerResourceAdaptor.java
In the case where validityTime of an SMS has expired, the SMS created due to MProc rules or deliveryReport SMS (Receipt) cause an SLEE Transcation Not started exception. This happens due to a call like this 
`this.schedulerRaSbbInterface.injectSmsOnFly(smst.getSmsSet());`
This piece of code reaches to `private boolean doInjectSms(SmsSet smsSet, boolean callFromSbb)` in the same java file but the callFromSbb by default is turned to true which in turn avoids creating an SLEE transaction and causes the exception.

The reason transaction doesn't exist is because this all happens in `OnTimerTick` method which is just a timer started by RA at start. Hence the callstack is under that timer and not in an SBB.

Solution is to not use schedulerRaSbbInterface but just directly call `doInjectSms` with callFromSbb set to false.

**Comment by vetss** [comment]
Thanks for feedback, but this issue is already fixed.
Please check: 
https://github.com/RestComm/smscgateway/issues/57

I am closing this issue.
