### ISSUE TITLE
GUI: Edit TCAP Stack properties values not working

### ISSUE THREAD

**Issue by FerUy** [RestComm/smscgateway#74]
When trying to execute any change on GUI regarding TCAP Stack properties (working in CLI), results in a javax.management.RuntimeErrorException. Stack trace shown in attached file:

[TCAP_DialogIdleTimeout.txt](https://github.com/RestComm/smscgateway/files/239273/TCAP_DialogIdleTimeout.txt)

**Comment by vetss** [comment]
This is an issue for JSS7 stack. I have created an issue there:
https://github.com/RestComm/jss7/issues/141
