### ISSUE TITLE
originatorSccpAddress=null when MProc originatingMask=SS7_HR

### ISSUE THREAD

**Issue by almayeen** [RestComm/smscgateway#75]

**Comment by nhanth87** [comment]
Hi @almayeen Can you explain more about this problem/issue?

Do you want to contribute for this?

**Comment by almayeen** [comment]
Hi @nhanth87 

I have ASP connected to SGW using SCTP<->M3UA<->SCCP<->MAP.

I have MProc based on  [originatingMask=SS7_HR , originatorSccpAddress=xxxxxxxx] for incoming SMS from SGW.

If SGW send MT_FORWARD_SHORT_MESSAGE_REQUEST with [CgPA=xxxxxxxx]  to ASP the MProc didn't act.

Yes, I want to contribute for this.

**Comment by vetss** [comment]
Hi @almayeen 

if you want to contribute please read "THE TELESTAX OPEN SOURCE PLAYBOOK" https://telestax.com/open-source/ and also you need to subscribe "Contributor License Agreement (CLA)".

**Comment by almayeen** [comment]
Hi @vetss 

Thanks.

I have been filled the "New Contributors" form.

**Comment by deruelle** [comment]
Thanks @almayeen. Well received, please follow our open source playbook and do a Pull request when ready. Looking forward to your contributions !

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/bb3b3be1d86114e2887078fc5634acfb142d05ff
https://github.com/RestComm/smscgateway/commit/941837b2bf12a535d2f8099630f2cc866d1a7ec0
https://github.com/RestComm/smscgateway/commit/dcbc6f304c424e56cbc60f579b3277bf5c9ed9aa

**Comment by deruelle** [comment]
@almayeen  Thanks ! Acknowledged at https://telestax.com/acknowledgements/
