### ISSUE TITLE
HrSriServerSbb Notification: logs the event "Created correlationId" as ERROR when sriBypass=true

### ISSUE THREAD

**Issue by almayeen** [RestComm/smscgateway#76]

**Comment by vetss** [comment]
HrSriServerSbb.setupSriRequest() - change to "Fine"

**Comment by almayeen** [comment]
Privet @vetss

We need to change from  "this.logger.severe(sb.toString());" 
to "this.logger.fine(sb.toString());" as you commented in HrSriServerSbb.setupSriRequest()

**Comment by vetss** [comment]
Hello @almayeen 

I have just merged you fix, thanks.
