### ISSUE TITLE
Make Intermediate Delivery Reports generation configurable

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#81]
We need to make introduced by https://github.com/RestComm/smscgateway/issues/62 functionality configurable (disabled / enabled) and disabled for default for backwork compatibility

**Comment by faizann** [comment]
Do we really need to make it configurable. Delivery reports are already configurable in SMSC. The intermediate delivery reports are only sent if requested in the SUBMIT_SM and Receipts are enabled in SMSC. So, in that case it seems a bit redundant to have another config just for Intermediate DLRs.

What do you think?

**Comment by vetss** [comment]
I am going to introduce it because this is some sort of new functionality that was disabled by previousely. 
It is needed so such new features will not break current behavour for sure at installed instanses of SMSC GW server.

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/16046e19c36dd1763a4ae213a269fa05f27b0148
https://github.com/RestComm/smscgateway/commit/a59d3e8c2a27151efa3a9716e75a028e3aa33d21
