### ISSUE TITLE
SmppTimeoutException

### ISSUE THREAD

**Issue by almayeen** [RestComm/smscgateway#84]
After the last update of smscgateway the ESME type:client close connection to the server directly after bind request.
The error log is:

Exception when trying to bind client SMPP connection for ESME systemId=esme1
com.cloudhopper.smpp.type.SmppTimeoutException: Unable to get response within [0 ms]

I think its due to ClientBindTimeout=0 for already exists ESME's, I just tried change in SmppClientOpsThread 
"config0.setBindTimeout(esme.getClientBindTimeout());"
to
"if(esme.getClientBindTimeout()>0){
            config0.setBindTimeout(esme.getClientBindTimeout());
}"
 and it's fixed.

**Comment by deruelle** [comment]
Thanks @almayeen for reporting the issue. Would you like to do a pull request for this ?

Please also sign the CLA at http://www.telestax.com/open-source/#Contribute so we can accept your contributions. Thanks !

**Comment by nhanth87** [comment]
Hi,
This issue is fixed by:
https://github.com/RestComm/smscgateway/commit/f30245948745592c7177da10a818832bd1cda78d

Br,
TN

**Comment by almayeen** [comment]
Hi @deruelle ,

You are welcome.

I already sign CLA before.

**Comment by vetss** [comment]
Hello @almayeen,

can you please check if you have downloaded the update with mentioned by @nhanth87 fix commit on board ?

**Comment by almayeen** [comment]
Hi @vetss 

I download the last update and the issue is fixed. thanks @nhanth87

**Comment by nhanth87** [comment]
Thanks for confirm @almayeen 
I closed this issue

Br,
TN
