### ISSUE TITLE
Multi GT support for multi networkId

### ISSUE THREAD

**Issue by nhanth87** [RestComm/smscgateway#93]
In some scenarios, SMSC GW requires different GTs for different networkId, but SMSC GW supports only one own GT now.

**Comment by faizann** [comment]
Isn't it already part of SMSC? GTs can be set per networkId via CLI
https://github.com/RestComm/smscgateway/blob/master/core/domain/src/main/java/org/mobicents/smsc/domain/SmscPropertiesManagement.java#L345

**Comment by nhanth87** [comment]
Hi, it's GT for Operator site. We want multi GT for SMSC GW (mean SMSC can have multiple GT number in it calling party address)

**Comment by vetss** [comment]
@nhanth87 please clarify which GT do you mean.
If you mean SMSC GW GT then we can make several GT for a single networkID area ?
For different networkID we can specify different GTs by command like:
smsc set scgt <globalTitle> networkid <networkId>

**Comment by faizann** [comment]
Is this an open issue still or current SMSC supports it?

**Comment by nhanth87** [comment]
hi,
it's a requested from one of our friend, multi-GT for every networkID, and we have discussed that's impossible due to jss7 multi-tenancy design (every nwid for every gt), so I would like to close it
