### ISSUE TITLE
Adding originatorSccpAddress / localSmscAddress / origNetworkId / NetworkId fields into CDR records

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#94]
We need to add originatorSccpAddress record into CDR records. This is a content of MO CallingPartyAddress SCCP address that means the originating VLR's SCCP address. This field let us know from what address a MO message was send to understand is a subscriber in roamingh or not and where.

1) Sms class contains "originatorSccpAddress" property that is set in MO procedure. But we does not store the field into cassandra database. We need to add it.
2) Add an extra field into CDR generator.
- originatorSccpAddress
- origNetworkId (a networkId via which a message has come to SMSC GW)
- networkId (a networkId via which a message was being delivered from SMSC GW)
- localSmscAddress (local SMSC GW GT that was used for sending of messages as ServiceCenter field in MAP address for SRI/MTFSM)

PS: See also #87 for other fields caring

Check also database update issue: https://github.com/RestComm/smscgateway/issues/95

**Comment by faizann** [comment]
I would like to suggest that we also store Originating SMSC GT (for  MT SMS). It is possible to infer SMSC GT based on the networkId but in case the GT is changed in configs the inferring will not be accurate for previous CDR records. This would require setting the GT during SRI request in the SmsSet. What do you think?

**Comment by vetss** [comment]
Hello @faizann 

Please explain what do you mean "Originating SMSC GT (for MT SMS)". Is is some field in MAP GSM traffic (which one) ?

**Comment by faizann** [comment]
It is the ServiceCenter field in MAP address for SRI/MTFSM. It is also the config name scgt in smsc that is set global or per networkId.

**Comment by vetss** [comment]
Hi @faizann 

I have added your new field into a first message of the issue.
I'd like to suggest to have also CDR fields set configurable so users may use only needed fields

**Comment by vetss** [comment]
This issue is fixed
